# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93ba837a488ce6c4715156ff18cd6a25"
application_url = "https://stark-shopify.trieve.ai"
embedded = true
name = "stark-trieve-extension"
handle = "stark-trieve-extension"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/app/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/app/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/app/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/app_subscriptions/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[auth]
redirect_urls = [
  "https://stark-shopify.trieve.ai/auth/callback",
  "https://stark-shopify.trieve.ai/auth/shopify/callback",
  "https://stark-shopify.trieve.ai/api/auth/callback"
]

[pos]
embedded = false
