# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "da7b1bca5d1c87d26eaea6b8c3f9090d"
application_url = "https://mac-case-shopify.trieve.ai"
embedded = true
name = "mac-case-trieve-extension"
handle = "mac-case-trieve-extension"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/app/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/app/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/app/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/app_subscriptions/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://mac-case-shopify.trieve.ai/api/auth",
  "https://mac-case-shopify.trieve.ai/api/shopify/callback",
  "https://mac-case-shopify.trieve.ai/auth/callback"
]

[pos]
embedded = false
