  1382-feature-better-handle-json-deserialize-error-message[m
  1535-bugfix-metadata-on-search-shows-object-object[m
  1542-feature-add-support-for-algolia-like-snippets[m
  1548-bugfix-search-and-rag-chat-buttons-pop-out-in-new-tab[m
  1567-feature-include-api-version-in-the-embedding_server-env-values[m
  1590-bugfix-pressing-esc-when-a-fullscreenmodal-is-opened-should-close-it[m
  1592-feature-ability-to-create-sample-dataset-directly-instead-of-only-being-able-to-add-sample-data-to-one[m
  1609-feature-add-num_value-as-one-of-the-default-filters-available-on-the-search-ui[m
  1610-bugfix-filter-modal-closing-when-clicking-on-a-non-interactive-element[m
  1611-feature-allow-for-the-ability-to-remove-filters-in-the-modal[m
  1633-feature-add-temperature-frequency_penalty-presence_penalty-stop_tokens-to-generate_from_chunks-request[m
  1636-bugfix-upload-file-not-working[m
  main[m
  remove-filter[m
* [32mvs/add-refresh-btn-chunk-count[m
  vs/metadata-values-show-up-as-object-object[m
  vs/use-futures-join-with-multiple-reranker-calls[m
  [31mremotes/origin/1000-feature-add-split_avg-request-param-to-create_chunk-for-long-docs[m
  [31mremotes/origin/1001-bugfix-duplicate-results-on-page-2+-for-hybrid-search-due-to-multiple-search-modes[m
  [31mremotes/origin/1005-feature-add-env-to-disable-full-text[m
  [31mremotes/origin/1024-feature-only-allow-for-deleting-orgs-on-free-tier[m
  [31mremotes/origin/1054-styling-make-show-metadata-button-in-dark-mode-look-better[m
  [31mremotes/origin/1060-cleanup-set-search-and-chat-analytics-correctly[m
  [31mremotes/origin/1078-bugfix-deleting-all-chunks-in-the-dataset-still-leaves-at-least-1-chunk-in-the-counts-table-should-be-0[m
  [31mremotes/origin/1089-bugfix-implement-graceful-shutdown-for-ingestion-server-httpstokiorstokiotopicsshutdown[m
  [31mremotes/origin/1108-feature-enable-redis-tls[m
  [31mremotes/origin/1120-cleanup-remove-cli[m
  [31mremotes/origin/1124-bugfix-pdf_from_range-route[m
  [31mremotes/origin/1126-feature-fork-algolia-docsearch-component-and-test-on-neon-docs-then-open-pr[m
  [31mremotes/origin/1141-optimization-timeout-for-redis--single-threaded[m
  [31mremotes/origin/1157-bugfix-default-embedding-model-for-datasets-in-admin-dash-should-be-jina[m
  [31mremotes/origin/1163-optimization-remove-duplicated-data-in-ingestion-redis-messages[m
  [31mremotes/origin/1164-bugfix-splade-embeddings-error-on-build[m
  [31mremotes/origin/1166-feature-allow-for-user-to-ignore-chunk_html-and-content-when-using-search-and-recommend[m
  [31mremotes/origin/1167-bugfix-group_tracking_ids-currently-do-not-work-because-qdrant-does-not-have-them[m
  [31mremotes/origin/1168-feature-instrument-all-search-and-recommendation-routes-with-sentry-at-various-timing-points[m
  [31mremotes/origin/1169-feature-also-return-group_tracking_id-everywhere-that-we-return-group_id[m
  [31mremotes/origin/1176-styling-apply-max-width-to-grouppage-component-frontmatter-in-search-ui[m
  [31mremotes/origin/1179-feature-allow-user-to-specify-group_size-0-for-group-search-and-recommendations[m
  [31mremotes/origin/1186-observability-add-dashboard-search-and-chat-uis-to-sentry[m
  [31mremotes/origin/1186-observability-add-dashboard-search-and-chat-uis-to-sentry-v2[m
  [31mremotes/origin/1192-feature-increase-perms-for-admin_api_key-such-that-it-allows-for-all-perms[m
  [31mremotes/origin/1196-bugfix-no-results-flash-on-search-ui[m
  [31mremotes/origin/1197-cleanup-remove-username-and-show_email-from-user-table[m
  [31mremotes/origin/1213-remove-defaulterror-and-use-serviceerror-for-everything-wrapping-the-internal-error-that-is-brought-up-through-sentry[m
  [31mremotes/origin/1231-feature-toggle-for-group-oriented-recommendations-in-ui[m
  [31mremotes/origin/1233-migration-write-migration-script-to-change-all-of-the-event-types-to-be-chunk_-instead-of-card_[m
  [31mremotes/origin/1241-feature-add-sentry-query-analytics-for-ingestion-workers-redis-queries[m
  [31mremotes/origin/1249-feature-add-support-for-additional-qdrant-recommendation-strategies[m
  [31mremotes/origin/1255-bugfix-ingest-worker-cpu-usage-spiking-when-redis-or-pg-die[m
  [31mremotes/origin/1258-feature-include-scores-on-recommendation-responses[m
  [31mremotes/origin/1263-bugfix-refreshing-the-page-of-search-ui-returns-no-results[m
  [31mremotes/origin/1279-cleanup-remove-sentry-event-capture-for-brpoplpush-and-ingestion_service[m
  [31mremotes/origin/1282-cleanup-remove-all-instances-of-reqwestclient-and-replace-with-ureq[m
  [31mremotes/origin/1296-feature-make-html--text-conversion-optional-with-request-param[m
  [31mremotes/origin/1303-feature-use-one-qdrant-connection-per-ingestion-worker-thread[m
  [31mremotes/origin/1314-feature-add-ability-to-be-able-to-go-directly-to-the-search-page-for-a-dataset[m
  [31mremotes/origin/1317-feature-associate-topics-to-an-arbitrary-key-instead-of-the-current-users-id[m
  [31mremotes/origin/1320-feature-keep-organization-state-on-refresh[m
  [31mremotes/origin/1323-feature-make-it-clear-on-users-page-for-an-org-that-you-cannot-view-because-you-only-have-admin-permissions[m
  [31mremotes/origin/1324-feature-search-within-group-by-tracking_id-instead-of-id[m
  [31mremotes/origin/1332-cleanup-remove-file_id-from-create_chunk[m
  [31mremotes/origin/1338-feature-in-create_embeddings-and-get_splade_embeddings-futuresjoin-all-the-requests-to-get-embeddings-if-its-embedding-more-than-30-items[m
  [31mremotes/origin/1342-bugfix-change-the-upload_file-worker-to-send-messages-in-bulk-in-a-similar-way-that-create_chunks-does[m
  [31mremotes/origin/1343-feature-automatically-rerun-query-when-mode-changes[m
  [31mremotes/origin/1354-feature-new-python-server-with-blocking-route-that-polls-to-see-if-all-tracking_ids-in-a-set-of-tracking_ids-exist[m
  [31mremotes/origin/1356-feature-show-tracking_id-on-search-ui[m
  [31mremotes/origin/1357-feature-add-configuration-key-to-turn-off-prompt_to_query-transformation-in-rag-api-routes[m
  [31mremotes/origin/1382-feature-better-handle-json-deserialize-error-message[m
  [31mremotes/origin/1396-bugfix-pagination-for-group-search[m
  [31mremotes/origin/1409-bugfix-slim_chunks-changing-ranking[m
  [31mremotes/origin/1409-bugfix-slim_chunks-changing-ranking-v2[m
  [31mremotes/origin/1463-feature-add-page_size-and-date_recency-options-to-search-ui[m
  [31mremotes/origin/1470-bugfix-restore-search_within_group-bar-on-group_page-for-search-ui[m
  [31mremotes/origin/1491-bugfix-check-box-chat-feature-in-search-ui-with-group-search[m
  [31mremotes/origin/1505-bugfix-issue-with-ingestion-worker-spiking-cpu-usage[m
  [31mremotes/origin/1505-bugfix-issue-with-ingestion-worker-spiking-cpu-usage-1[m
  [31mremotes/origin/1519-feature-env-flag-to-specify-what-sizes-of-embeddings-you-want-to-create-within-qdrant[m
  [31mremotes/origin/1530-feature-backfill-page-of-autocomplete-with-normal-results-from-search_chunk-handler-function[m
  [31mremotes/origin/1535-bugfix-metadata-on-search-shows-object-object[m
  [31mremotes/origin/1542-feature-add-support-for-algolia-like-snippets[m
  [31mremotes/origin/1548-bugfix-search-and-rag-chat-buttons-pop-out-in-new-tab[m
  [31mremotes/origin/1567-feature-include-api-version-in-the-embedding_server-env-values[m
  [31mremotes/origin/1581-bugfix-rag-should-work-well-on-use-cases-where-the-second-message-asks-can-you-write-an-example-based-on-the-first-response[m
  [31mremotes/origin/1590-bugfix-pressing-esc-when-a-fullscreenmodal-is-opened-should-close-it[m
  [31mremotes/origin/1592-feature-ability-to-create-sample-dataset-directly-instead-of-only-being-able-to-add-sample-data-to-one[m
  [31mremotes/origin/1609-feature-add-num_value-as-one-of-the-default-filters-available-on-the-search-ui[m
  [31mremotes/origin/1610-bugfix-filter-modal-closing-when-clicking-on-a-non-interactive-element[m
  [31mremotes/origin/1611-feature-allow-for-the-ability-to-remove-filters-in-the-modal[m
  [31mremotes/origin/1631-cleanup-remove-monitoring_server[m
  [31mremotes/origin/1633-feature-add-temperature-frequency_penalty-presence_penalty-stop_tokens-to-generate_from_chunks-request[m
  [31mremotes/origin/1636-bugfix-upload-file-not-working[m
  [31mremotes/origin/239-feature-get-your-own-private-cards-on-main-search[m
  [31mremotes/origin/606-bugfix-filters-on-fulltext-search-are-causing-thread-panic[m
  [31mremotes/origin/608-feature-it-should-function-correctly-if-there-are-multiple-sets-of-quotes-in-filters[m
  [31mremotes/origin/609-feature-add-resource-routes-based-on-tracking_id[m
  [31mremotes/origin/612-feature-if-the-words-in-a-card-are-the-lines_before_show-env-15-then-dont-have-the-show-more-button[m
  [31mremotes/origin/615-feature-allow-for-arbitrary-metadata-on-file-upload[m
  [31mremotes/origin/617-bugfix-always-abort-in-oncleanup-instead-of-return[m
  [31mremotes/origin/631-feature-time-range-filter[m
  [31mremotes/origin/643-feature-support-vectara-corpora-logic[m
  [31mremotes/origin/643-feature-support-vectara-corpora-logic-1[m
  [31mremotes/origin/784-cleanup-rename-server-crate-to-trieve-server[m
  [31mremotes/origin/784-cleanup-rename-server-crate-to-trieve-server-2[m
  [31mremotes/origin/804-bugfix-changes-required-for-search-client[m
  [31mremotes/origin/831-cleanup-version-openapi-docs-properly[m
  [31mremotes/origin/878-feature-set-embedding-model-on-dataset-creation-and-lock-it[m
  [31mremotes/origin/881-feature-show-all-keys-by-default-on-search-ui[m
  [31mremotes/origin/914-improvement-tag_set-should-be-a-list-of-tags-not-comma-separated-string[m
  [31mremotes/origin/979-feature-increase-free-tier-for-file-storage[m
  [31mremotes/origin/999-feature-add-group_tracking_id-as-a-param-to-create_chunk[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/add-tracking-id[m
  [31mremotes/origin/au/bullseye-to-bookworm[m
  [31mremotes/origin/clear-dataset[m
  [31mremotes/origin/copy-api-key[m
  [31mremotes/origin/densumesh-patch-1[m
  [31mremotes/origin/drewh/active-search[m
  [31mremotes/origin/drewh/add-dashboard-to-readme-env[m
  [31mremotes/origin/drewh/analytics-boilerplate[m
  [31mremotes/origin/drewh/analytics-site[m
  [31mremotes/origin/drewh/chat-citation-sizing[m
  [31mremotes/origin/drewh/chat-css-refresh[m
  [31mremotes/origin/drewh/chat-filters[m
  [31mremotes/origin/drewh/chat-shift-enter[m
  [31mremotes/origin/drewh/clickhouse-for-delete-queue[m
  [31mremotes/origin/drewh/create-sample-dataset[m
  [31mremotes/origin/drewh/css-fixups[m
  [31mremotes/origin/drewh/dataset-search-fix[m
  [31mremotes/origin/drewh/filters-for-rag[m
  [31mremotes/origin/drewh/fix-agario-graph[m
  [31mremotes/origin/drewh/fix-delete-dataset[m
  [31mremotes/origin/drewh/fix-monorepo[m
  [31mremotes/origin/drewh/fix-muti-message-chat[m
  [31mremotes/origin/drewh/fix-tiny-editor[m
  [31mremotes/origin/drewh/long-dataset-list[m
  [31mremotes/origin/drewh/more-api-key-formats[m
  [31mremotes/origin/drewh/move-dashboard-api-keys[m
  [31mremotes/origin/drewh/org-deletion-header[m
  [31mremotes/origin/drewh/other-routes-confirm-membership[m
  [31mremotes/origin/drewh/other-stats[m
  [31mremotes/origin/drewh/remove-sentry-from-template-env[m
  [31mremotes/origin/drewh/show-chunk-count-dashboard[m
  [31mremotes/origin/drewh/split-delimiters[m
  [31mremotes/origin/drewh/vs-code-fix[m
  [31mremotes/origin/drewh/working-monorepo[m
  [31mremotes/origin/ds/add-autocomplete-fulltext[m
  [31mremotes/origin/ds/add-customizable-sizing-for-pages-and-groups[m
  [31mremotes/origin/ds/add-dashboard-to-monorepo[m
  [31mremotes/origin/ds/add-dataset-selector-to-search[m
  [31mremotes/origin/ds/add-dataset-tracking-id[m
  [31mremotes/origin/ds/add-embedding-query-prefix-to-dashboard[m
  [31mremotes/origin/ds/add-errors-for-file-upload[m
  [31mremotes/origin/ds/add-filter-field-dropdown[m
  [31mremotes/origin/ds/add-group-size-option[m
  [31mremotes/origin/ds/add-highlight-context[m
  [31mremotes/origin/ds/add-id-filters[m
  [31mremotes/origin/ds/add-image-url-field[m
  [31mremotes/origin/ds/add-index-on-key-has[m
  [31mremotes/origin/ds/add-indexes-on-org-and-dataset-joins[m
  [31mremotes/origin/ds/add-limit-for-bulk-upload[m
  [31mremotes/origin/ds/add-location-index[m
  [31mremotes/origin/ds/add-multiple-qdrant-collections[m
  [31mremotes/origin/ds/add-new-embedding-model[m
  [31mremotes/origin/ds/add-new-event-types[m
  [31mremotes/origin/ds/add-new-filter-conditions[m
  [31mremotes/origin/ds/add-numeric-column[m
  [31mremotes/origin/ds/add-option-to-turn-off-rerank[m
  [31mremotes/origin/ds/add-own-embedding-vector[m
  [31mremotes/origin/ds/add-qdrant-dataset-config[m
  [31mremotes/origin/ds/add-search-params[m
  [31mremotes/origin/ds/add-tag-weights[m
  [31mremotes/origin/ds/add-thread-nnum[m
  [31mremotes/origin/ds/add-time_stamp-formattin[m
  [31mremotes/origin/ds/add-toast-on-user-invite[m
  [31mremotes/origin/ds/add-tracking-id-to-groups[m
  [31mremotes/origin/ds/add-trunction-to-embeddings[m
  [31mremotes/origin/ds/added-correct-counts[m
  [31mremotes/origin/ds/analytics-suite[m
  [31mremotes/origin/ds/api-key-roles[m
  [31mremotes/origin/ds/api-key-table[m
  [31mremotes/origin/ds/autocomplete[m
  [31mremotes/origin/ds/better-suggested-query-gen[m
  [31mremotes/origin/ds/branch-fix[m
  [31mremotes/origin/ds/bugfis-for-open-chunk[m
  [31mremotes/origin/ds/bugfix-fix-dataset-id-in-ulr[m
  [31mremotes/origin/ds/bugfix-group-search[m
  [31mremotes/origin/ds/change-back-tracking-id[m
  [31mremotes/origin/ds/change-openrouter-env-name[m
  [31mremotes/origin/ds/change-search-for-file-upload[m
  [31mremotes/origin/ds/chat-bugfixes[m
  [31mremotes/origin/ds/chunk-not-found-error[m
  [31mremotes/origin/ds/client-envs[m
  [31mremotes/origin/ds/collection-search[m
  [31mremotes/origin/ds/create-org-on-register[m
  [31mremotes/origin/ds/cross-encoder-limit[m
  [31mremotes/origin/ds/custom-embedding-sizes[m
  [31mremotes/origin/ds/custom-reranker[m
  [31mremotes/origin/ds/customizable-highlights[m
  [31mremotes/origin/ds/dashboard-embedding-model-fixx[m
  [31mremotes/origin/ds/dataset-as-search-param[m
  [31mremotes/origin/ds/dataset-usage-count[m
  [31mremotes/origin/ds/date-range-filters[m
  [31mremotes/origin/ds/date-recency-with-param[m
  [31mremotes/origin/ds/default-org-name[m
  [31mremotes/origin/ds/delete-chunk-with-files[m
  [31mremotes/origin/ds/delete-chunks-with-collections[m
  [31mremotes/origin/ds/delete-datasets[m
  [31mremotes/origin/ds/deprecate-tracking-id-routes[m
  [31mremotes/origin/ds/event-filtering[m
  [31mremotes/origin/ds/events-on-card-creation[m
  [31mremotes/origin/ds/events-page-optimizations[m
  [31mremotes/origin/ds/example-dataset-frontend[m
  [31mremotes/origin/ds/file-tracking-id[m
  [31mremotes/origin/ds/file-worker[m
  [31mremotes/origin/ds/filters-for-recommendations[m
  [31mremotes/origin/ds/first-step-to-convert-tag-set[m
  [31mremotes/origin/ds/fix-api-key-role-bug[m
  [31mremotes/origin/ds/fix-chat-ui[m
  [31mremotes/origin/ds/fix-dataset-and-org-selector[m
  [31mremotes/origin/ds/fix-delete-router[m
  [31mremotes/origin/ds/fix-delete-update[m
  [31mremotes/origin/ds/fix-deleting-datasets-with-tracking[m
  [31mremotes/origin/ds/fix-filter-modal[m
  [31mremotes/origin/ds/fix-group-edit-page[m
  [31mremotes/origin/ds/fix-group-hybrid-search[m
  [31mremotes/origin/ds/fix-group-recommend[m
  [31mremotes/origin/ds/fix-header-bug[m
  [31mremotes/origin/ds/fix-highlighting[m
  [31mremotes/origin/ds/fix-hybrid-search-rank[m
  [31mremotes/origin/ds/fix-login-html[m
  [31mremotes/origin/ds/fix-logout-route[m
  [31mremotes/origin/ds/fix-must-not-filters[m
  [31mremotes/origin/ds/fix-pagination-for-frontend[m
  [31mremotes/origin/ds/fix-qdrant-payload-size-error[m
  [31mremotes/origin/ds/fix-rerank-bug[m
  [31mremotes/origin/ds/fix-score-error[m
  [31mremotes/origin/ds/fix-search-client-doc-mismatch[m
  [31mremotes/origin/ds/fix-spare-encoder-bug[m
  [31mremotes/origin/ds/fix-streaming-issue[m
  [31mremotes/origin/ds/fix-threshold-value[m
  [31mremotes/origin/ds/fix-timestamp-ordering[m
  [31mremotes/origin/ds/fix-tracking-id-errors[m
  [31mremotes/origin/ds/fix-weight-bug][m
  [31mremotes/origin/ds/full-text-recommendations[m
  [31mremotes/origin/ds/generate-off-card[m
  [31mremotes/origin/ds/group-and-file-pages[m
  [31mremotes/origin/ds/group-file-download[m
  [31mremotes/origin/ds/group-metadata-and-tag-set[m
  [31mremotes/origin/ds/group-route-with-tracking-ids[m
  [31mremotes/origin/ds/guard-routes-by-perms[m
  [31mremotes/origin/ds/highlight-improvements[m
  [31mremotes/origin/ds/hybrid-score-threshold[m
  [31mremotes/origin/ds/improve-local-login[m
  [31mremotes/origin/ds/increase-delete-batch-size[m
  [31mremotes/origin/ds/increase-timeout-on-qdrant[m
  [31mremotes/origin/ds/ingestion-microservice[m
  [31mremotes/origin/ds/invalidate-cache-on-env-update[m
  [31mremotes/origin/ds/keycloak-auth[m
  [31mremotes/origin/ds/keycloak-theming[m
  [31mremotes/origin/ds/local-login-page[m
  [31mremotes/origin/ds/make-group-hybrid-better[m
  [31mremotes/origin/ds/make-hybrid-group-search-better[m
  [31mremotes/origin/ds/make-metadata-filtering-faster[m
  [31mremotes/origin/ds/make-user-orgs-seperate-from-identity[m
  [31mremotes/origin/ds/make-weights-on[m
  [31mremotes/origin/ds/migrate-to-candle[m
  [31mremotes/origin/ds/minikube-setup[m
  [31mremotes/origin/ds/modify-delete-requests[m
  [31mremotes/origin/ds/move-all-metadata-to-qdrant[m
  [31mremotes/origin/ds/move-cross-encoder[m
  [31mremotes/origin/ds/move-to-ureq-for-embeddings[m
  [31mremotes/origin/ds/move_collections_to_dataets[m
  [31mremotes/origin/ds/move_collections_to_dataset[m
  [31mremotes/origin/ds/negation-operator[m
  [31mremotes/origin/ds/new-auth-middleware[m
  [31mremotes/origin/ds/new-index-tokenizer[m
  [31mremotes/origin/ds/new-rag-prompt[m
  [31mremotes/origin/ds/notifications-with-datasets[m
  [31mremotes/origin/ds/only-ids-request[m
  [31mremotes/origin/ds/onnx-model[m
  [31mremotes/origin/ds/open-health-route[m
  [31mremotes/origin/ds/openrouter-support[m
  [31mremotes/origin/ds/organization-or-dataset-guard[m
  [31mremotes/origin/ds/parallize-cross-encoder-calls[m
  [31mremotes/origin/ds/prefilter-tag-set[m
  [31mremotes/origin/ds/qdrant-filtering[m
  [31mremotes/origin/ds/qdrant-filters[m
  [31mremotes/origin/ds/qdrant-partitioning[m
  [31mremotes/origin/ds/qdrant-tokenizer-fix[m
  [31mremotes/origin/ds/quote-and-negate-word-in-qdrant[m
  [31mremotes/origin/ds/rag-with-doc-nums[m
  [31mremotes/origin/ds/range-filters[m
  [31mremotes/origin/ds/refactor-search-route-v2[m
  [31mremotes/origin/ds/refactor-search-routes[m
  [31mremotes/origin/ds/refactor-usage-to-table[m
  [31mremotes/origin/ds/remove-collisions-from-collections[m
  [31mremotes/origin/ds/remove-content-field[m
  [31mremotes/origin/ds/remove-file-mime-type[m
  [31mremotes/origin/ds/remove-github-config-param[m
  [31mremotes/origin/ds/remove-invitation-expiration[m
  [31mremotes/origin/ds/remove-name-key-constriant[m
  [31mremotes/origin/ds/remove-sensitive-info[m
  [31mremotes/origin/ds/remove-side-and-normal-chat[m
  [31mremotes/origin/ds/replace-redis-with-rabbitmq[m
  [31mremotes/origin/ds/replace-stores-with-context[m
  [31mremotes/origin/ds/return-cross-encoder-if-empty[m
  [31mremotes/origin/ds/rust-openapi-compat[m
  [31mremotes/origin/ds/s3-for-images[m
  [31mremotes/origin/ds/scoped_api_keys[m
  [31mremotes/origin/ds/search-and-stores-fix[m
  [31mremotes/origin/ds/search-over-group-reccommendations[m
  [31mremotes/origin/ds/set-topic-name[m
  [31mremotes/origin/ds/signed-s3-url[m
  [31mremotes/origin/ds/simplify-middleware[m
  [31mremotes/origin/ds/soft-delete-dataset[m
  [31mremotes/origin/ds/soft-delete-organizations[m
  [31mremotes/origin/ds/stores-for-envs[m
  [31mremotes/origin/ds/suggested-queries[m
  [31mremotes/origin/ds/support-event-dashboard[m
  [31mremotes/origin/ds/tag-set-to-array[m
  [31mremotes/origin/ds/tantivy-index[m
  [31mremotes/origin/ds/tantivy-recovery[m
  [31mremotes/origin/ds/text-search-rerank[m
  [31mremotes/origin/ds/tf-cli[m
  [31mremotes/origin/ds/timing-for-search[m
  [31mremotes/origin/ds/update-api_key-spec[m
  [31mremotes/origin/ds/update-groups-from-route[m
  [31mremotes/origin/ds/update-openapi-spec[m
  [31mremotes/origin/ds/update-qdrant-payload[m
  [31mremotes/origin/ds/update-to-ingestion-micro[m
  [31mremotes/origin/ds/upsert-chunk-group[m
  [31mremotes/origin/ds/usage-metrics[m
  [31mremotes/origin/ds/use-core-num-for-threads[m
  [31mremotes/origin/ds/use-pg-for-metadata[m
  [31mremotes/origin/ds/user-management-table[m
  [31mremotes/origin/ds/user-management-ui[m
  [31mremotes/origin/ds/view-and-manage-invitations-on-dashboard[m
  [31mremotes/origin/ds/weights-for-cards[m
  [31mremotes/origin/ey/arb-files[m
  [31mremotes/origin/ey/bugfix-chat-always-show-all-cards[m
  [31mremotes/origin/ey/bugfix-chatpopup[m
  [31mremotes/origin/ey/bugfix-too-small-chunks[m
  [31mremotes/origin/ey/card-component-fixes-minor[m
  [31mremotes/origin/ey/lint-required-url-pagination[m
  [31mremotes/origin/ey/lopdf-attempt[m
  [31mremotes/origin/ey/openapi-spec[m
  [31mremotes/origin/ey/styling-slightly-improved-filters[m
  [31mremotes/origin/ey/version-tag-redis[m
  [31mremotes/origin/fa/add-sentry[m
  [31mremotes/origin/fa/add-sentry-scopes[m
  [31mremotes/origin/fa/add-span-over-qdrant[m
  [31mremotes/origin/fa/add-support-for-3072-vectors[m
  [31mremotes/origin/fa/add-transaction-finish[m
  [31mremotes/origin/fa/alternate-embedding-server[m
  [31mremotes/origin/fa/api-key-on-embeddings[m
  [31mremotes/origin/fa/base-hostname-env[m
  [31mremotes/origin/fa/better-github-actions[m
  [31mremotes/origin/fa/better-qdrant-configuration[m
  [31mremotes/origin/fa/better-qdrant-create-bin[m
  [31mremotes/origin/fa/bookmark-tracking-id[m
  [31mremotes/origin/fa/bugfix-dashboard-model-selector[m
  [31mremotes/origin/fa/bugfix-fix-sentry-tracing[m
  [31mremotes/origin/fa/bugfix-jina-code[m
  [31mremotes/origin/fa/bugfix-llm-base-url[m
  [31mremotes/origin/fa/bugfix-truncate-for-splade-embeddings[m
  [31mremotes/origin/fa/build-cache-to-different-repo[m
  [31mremotes/origin/fa/bulk-upload-operator[m
  [31mremotes/origin/fa/bulk_ingestion_testing[m
  [31mremotes/origin/fa/bump-keycloak-version[m
  [31mremotes/origin/fa/bump-openaidive[m
  [31mremotes/origin/fa/card-collection-return-200[m
  [31mremotes/origin/fa/cast-result-from-embedding-server[m
  [31mremotes/origin/fa/change-action-name[m
  [31mremotes/origin/fa/change-tagset-to-keyword[m
  [31mremotes/origin/fa/chat-refactor[m
  [31mremotes/origin/fa/chat-to-spa[m
  [31mremotes/origin/fa/chat-ui[m
  [31mremotes/origin/fa/chunk-metadata-docs[m
  [31mremotes/origin/fa/ci-faster-button[m
  [31mremotes/origin/fa/ci-push-action[m
  [31mremotes/origin/fa/clarity-correct-error-message[m
  [31mremotes/origin/fa/claude-usability[m
  [31mremotes/origin/fa/cleaner-group-errors[m
  [31mremotes/origin/fa/cleanup-pg-calls[m
  [31mremotes/origin/fa/clearer-things[m
  [31mremotes/origin/fa/clippy[m
  [31mremotes/origin/fa/collisions-as-envflag[m
  [31mremotes/origin/fa/configure-model-name[m
  [31mremotes/origin/fa/correct-error-on-point-id[m
  [31mremotes/origin/fa/create-group-before-cards[m
  [31mremotes/origin/fa/create-in-bulk[m
  [31mremotes/origin/fa/custom-node-taints[m
  [31mremotes/origin/fa/dashboard-bugfix-jina-code[m
  [31mremotes/origin/fa/dashboard-ci-action[m
  [31mremotes/origin/fa/dataset[m
  [31mremotes/origin/fa/dataset-cascade-delete[m
  [31mremotes/origin/fa/dataset-choose-box[m
  [31mremotes/origin/fa/dataset-combobox[m
  [31mremotes/origin/fa/dataset-configuration[m
  [31mremotes/origin/fa/dataset-extras[m
  [31mremotes/origin/fa/dataset-in-session[m
  [31mremotes/origin/fa/deadpool-redis[m
  [31mremotes/origin/fa/delete-worker-helm[m
  [31mremotes/origin/fa/different-ingestion-architecture[m
  [31mremotes/origin/fa/docker-compose-profiles[m
  [31mremotes/origin/fa/docker-file-change-copy-command[m
  [31mremotes/origin/fa/dockerfile-ssl[m
  [31mremotes/origin/fa/dockerfile-tmp-folder[m
  [31mremotes/origin/fa/dockerfile-updates[m
  [31mremotes/origin/fa/eks-improovements[m
  [31mremotes/origin/fa/embedding[m
  [31mremotes/origin/fa/embedding-semaphore[m
  [31mremotes/origin/fa/embedding-server-empty-vec[m
  [31mremotes/origin/fa/embedding-server-multigpu[m
  [31mremotes/origin/fa/embedding-server-patches[m
  [31mremotes/origin/fa/embedding-server-tracing[m
  [31mremotes/origin/fa/even-smaller-docker[m
  [31mremotes/origin/fa/extra-logs-on-qdrant-errors[m
  [31mremotes/origin/fa/extra-sentry-context[m
  [31mremotes/origin/fa/faster-pg-mayb[m
  [31mremotes/origin/fa/faster-server-runtimes[m
  [31mremotes/origin/fa/faster-splade[m
  [31mremotes/origin/fa/fix-ci-action-from-triggering-and-add-concurrency[m
  [31mremotes/origin/fa/fix-no-ocr-image[m
  [31mremotes/origin/fa/fix-pagination[m
  [31mremotes/origin/fa/fix-topic-delete-route[m
  [31mremotes/origin/fa/fix-update-route-to-correct-name[m
  [31mremotes/origin/fa/gcloud-single-zone[m
  [31mremotes/origin/fa/get-signed-url[m
  [31mremotes/origin/fa/google-cloud-support[m
  [31mremotes/origin/fa/health-check-route-on-root[m
  [31mremotes/origin/fa/helm-repo-guide[m
  [31mremotes/origin/fa/hotfix-embedding-server-stays-compat[m
  [31mremotes/origin/fa/hybrid-as-default[m
  [31mremotes/origin/fa/id-or-name-in-organization-header[m
  [31mremotes/origin/fa/ids-tracking-ids-unwrap[m
  [31mremotes/origin/fa/image-key[m
  [31mremotes/origin/fa/ingest-microservice[m
  [31mremotes/origin/fa/ingestion-ci[m
  [31mremotes/origin/fa/ingestion-multithreaded[m
  [31mremotes/origin/fa/ingestion-threads[m
  [31mremotes/origin/fa/jina-code[m
  [31mremotes/origin/fa/jina-code-api-key[m
  [31mremotes/origin/fa/larger-cluster[m
  [31mremotes/origin/fa/less-threads[m
  [31mremotes/origin/fa/make-splade-embeddings-outside-of-operator[m
  [31mremotes/origin/fa/middleware-speedup[m
  [31mremotes/origin/fa/more-docker-fixes[m
  [31mremotes/origin/fa/more-more-logs[m
  [31mremotes/origin/fa/more-reliable-queue[m
  [31mremotes/origin/fa/more-retries[m
  [31mremotes/origin/fa/more-stats[m
  [31mremotes/origin/fa/no-empty-splade-embedding[m
  [31mremotes/origin/fa/no-sharing[m
  [31mremotes/origin/fa/ocr-as-feature-flag-smaller-dockerfile[m
  [31mremotes/origin/fa/ocr-image-fixed[m
  [31mremotes/origin/fa/only-return-indexed-points[m
  [31mremotes/origin/fa/openAPI-headers[m
  [31mremotes/origin/fa/openapi-errors[m
  [31mremotes/origin/fa/ops-cargo-fmt-action[m
  [31mremotes/origin/fa/optimize-docker-files[m
  [31mremotes/origin/fa/optimize-release-builds[m
  [31mremotes/origin/fa/organization-choose-box[m
  [31mremotes/origin/fa/perf-no-reqwest-client[m
  [31mremotes/origin/fa/private-cards-main-search[m
  [31mremotes/origin/fa/proper-ingestion[m
  [31mremotes/origin/fa/pull-s3-from-instance-profile[m
  [31mremotes/origin/fa/qdrant-microservices[m
  [31mremotes/origin/fa/qdrant-unwrap-bugfix[m
  [31mremotes/origin/fa/qdrant-update-doesnt-fail-early[m
  [31mremotes/origin/fa/qdrant-upload-worker-thread[m
  [31mremotes/origin/fa/quantize-env-flag[m
  [31mremotes/origin/fa/redoc-ci-action[m
  [31mremotes/origin/fa/refactor-calculate-splade-embedding-earlier[m
  [31mremotes/origin/fa/remove-404-logs[m
  [31mremotes/origin/fa/remove-all-qdrant-unwraps[m
  [31mremotes/origin/fa/remove-arm-images[m
  [31mremotes/origin/fa/remove-indexes[m
  [31mremotes/origin/fa/remove-tagset-prefilter[m
  [31mremotes/origin/fa/revert-openai-to-azure[m
  [31mremotes/origin/fa/rust-actions[m
  [31mremotes/origin/fa/rust-actions-2[m
  [31mremotes/origin/fa/rust-actions-fix[m
  [31mremotes/origin/fa/rust-checks-to-single-action[m
  [31mremotes/origin/fa/s3-docker-ci-caching[m
  [31mremotes/origin/fa/search-dockerfile-improovements[m
  [31mremotes/origin/fa/search-eslint-errors[m
  [31mremotes/origin/fa/search-over-groups-in-ui[m
  [31mremotes/origin/fa/sentry-doesnt-die[m
  [31mremotes/origin/fa/sentry-for-ingest-sentry-for-ingest[m
  [31mremotes/origin/fa/sentry-for-main-server[m
  [31mremotes/origin/fa/sentry-tracing[m
  [31mremotes/origin/fa/seperate-caches[m
  [31mremotes/origin/fa/set-aws-region[m
  [31mremotes/origin/fa/support-arm64-docker-images[m
  [31mremotes/origin/fa/support-azure-openai[m
  [31mremotes/origin/fa/switch-to-async[m
  [31mremotes/origin/fa/switch-to-bb8[m
  [31mremotes/origin/fa/tag-set-logic[m
  [31mremotes/origin/fa/tag-set-table[m
  [31mremotes/origin/fa/tagged-images[m
  [31mremotes/origin/fa/test-two[m
  [31mremotes/origin/fa/tracking-id-unique-per-dataset[m
  [31mremotes/origin/fa/unique-organization-names-generate-if-needed[m
  [31mremotes/origin/fa/update-embedding[m
  [31mremotes/origin/fa/updated-helm-and-terraform-config[m
  [31mremotes/origin/fa/updated-hosting-guide[m
  [31mremotes/origin/fa/uriEncode-getfile[m
  [31mremotes/origin/fa/visibility-print-ids-on-failure[m
  [31mremotes/origin/fa/wip-removing-chunk-metadata-with-file-data[m
  [31mremotes/origin/feature/hybrid-search[m
  [31mremotes/origin/fix-number-input[m
  [31mremotes/origin/group-updates[m
  [31mremotes/origin/hotfix-fix-python-docker[m
  [31mremotes/origin/kube-experiment-fork[m
  [31mremotes/origin/main[m
  [31mremotes/origin/patch/fix-redoc[m
  [31mremotes/origin/refactor-filter-modal[m
  [31mremotes/origin/release/0.1.0[m
  [31mremotes/origin/release/0.1.9[m
  [31mremotes/origin/release/0.2.0[m
  [31mremotes/origin/remove-filter[m
  [31mremotes/origin/remove-unwrap[m
  [31mremotes/origin/revert-1376-ds/add-location-index[m
  [31mremotes/origin/revert-1398-ds/tag-set-to-array[m
  [31mremotes/origin/revert-1420-ds/remove-content-field[m
  [31mremotes/origin/revert-1506-ds/first-step-to-convert-tag-set[m
  [31mremotes/origin/revert-1561-fa/tag-set-logic[m
  [31mremotes/origin/revert-pgbm25[m
  [31mremotes/origin/send-email-org-signup[m
  [31mremotes/origin/server-ci[m
  [31mremotes/origin/server-conf-hyde[m
  [31mremotes/origin/sk/accept-multiple-groups-on-create-chunk[m
  [31mremotes/origin/sk/add-404-responses-to-resource-get-routes[m
  [31mremotes/origin/sk/add-auth-to-cardcollections[m
  [31mremotes/origin/sk/add-auth-to-collections[m
  [31mremotes/origin/sk/add-auth-to-generate-off-cards-route[m
  [31mremotes/origin/sk/add-auth-to-routes[m
  [31mremotes/origin/sk/add-back-brpoplpush-ctx[m
  [31mremotes/origin/sk/add-custom-split-token-support[m
  [31mremotes/origin/sk/add-delete-organization-route[m
  [31mremotes/origin/sk/add-descriptions-to-openapi-spec[m
  [31mremotes/origin/sk/add-embedding-model-name-as-config-param[m
  [31mremotes/origin/sk/add-linguist-controls-to-ignore-non-rust[m
  [31mremotes/origin/sk/add-lnx-remove-pgbm25[m
  [31mremotes/origin/sk/add-names-to-plans[m
  [31mremotes/origin/sk/add-opengraph-tags[m
  [31mremotes/origin/sk/add-orgs-to-slim-user[m
  [31mremotes/origin/sk/add-pdf-download[m
  [31mremotes/origin/sk/add-resp-text-to-embedding-call[m
  [31mremotes/origin/sk/add-role-to-invites[m
  [31mremotes/origin/sk/add-route-to-fetch-plans[m
  [31mremotes/origin/sk/add-stripe-customers-table[m
  [31mremotes/origin/sk/add-support-for-bgem3[m
  [31mremotes/origin/sk/add-tag-set-array-index[m
  [31mremotes/origin/sk/add-weight-to-create-edit-chunk-forms[m
  [31mremotes/origin/sk/allow-for-delete-dataset-chunk-metadata-collisions[m
  [31mremotes/origin/sk/allow-promo-codes[m
  [31mremotes/origin/sk/batch-embeddings[m
  [31mremotes/origin/sk/bugfix-add-timeout[m
  [31mremotes/origin/sk/bugfix-api-key-role[m
  [31mremotes/origin/sk/bugfix-average-embedding-error[m
  [31mremotes/origin/sk/bugfix-best-score-strategy[m
  [31mremotes/origin/sk/bugfix-chat-ui[m
  [31mremotes/origin/sk/bugfix-chunks-in-group[m
  [31mremotes/origin/sk/bugfix-collection-search[m
  [31mremotes/origin/sk/bugfix-cross-encoder-rerank[m
  [31mremotes/origin/sk/bugfix-date-range-score-array[m
  [31mremotes/origin/sk/bugfix-deleting-datasets-with-files[m
  [31mremotes/origin/sk/bugfix-double-loading-crab[m
  [31mremotes/origin/sk/bugfix-drain-being-longer-than-vec[m
  [31mremotes/origin/sk/bugfix-edit[m
  [31mremotes/origin/sk/bugfix-edit-view-chunk-pages[m
  [31mremotes/origin/sk/bugfix-embedding-server-json-encode-float32-error[m
  [31mremotes/origin/sk/bugfix-escaped-quote-words[m
  [31mremotes/origin/sk/bugfix-extend-repositioning-autocomplete-results[m
  [31mremotes/origin/sk/bugfix-feature-within-group-search-tracking-id[m
  [31mremotes/origin/sk/bugfix-file-id-for-chunk-group[m
  [31mremotes/origin/sk/bugfix-file-upload[m
  [31mremotes/origin/sk/bugfix-file-upload-2[m
  [31mremotes/origin/sk/bugfix-get-suggested-queries-route[m
  [31mremotes/origin/sk/bugfix-group-chunk-recs[m
  [31mremotes/origin/sk/bugfix-group-update-error[m
  [31mremotes/origin/sk/bugfix-handle-when-metadata-is-invalid[m
  [31mremotes/origin/sk/bugfix-hotfix[m
  [31mremotes/origin/sk/bugfix-hybrid[m
  [31mremotes/origin/sk/bugfix-image-subsystem[m
  [31mremotes/origin/sk/bugfix-image-upload[m
  [31mremotes/origin/sk/bugfix-ingestion-worker-panic[m
  [31mremotes/origin/sk/bugfix-json-payload-too-large[m
  [31mremotes/origin/sk/bugfix-make-error-message-on-create-chunk-queue-route-accurate[m
  [31mremotes/origin/sk/bugfix-metadata-range-filters[m
  [31mremotes/origin/sk/bugfix-nested-highlights[m
  [31mremotes/origin/sk/bugfix-not-able-to-select-openai[m
  [31mremotes/origin/sk/bugfix-num-value-latency[m
  [31mremotes/origin/sk/bugfix-observability-duplicate-chunk-data[m
  [31mremotes/origin/sk/bugfix-ocr-image[m
  [31mremotes/origin/sk/bugfix-offset-10-instead-of-limit-for-search[m
  [31mremotes/origin/sk/bugfix-openapi-spec[m
  [31mremotes/origin/sk/bugfix-order-on-recs-and-group-search[m
  [31mremotes/origin/sk/bugfix-org-delete[m
  [31mremotes/origin/sk/bugfix-page-size-in-hybrid-and-hybrid-slim-chunks[m
  [31mremotes/origin/sk/bugfix-pdf-from-range-organization-id-spelling[m
  [31mremotes/origin/sk/bugfix-plans-fetch-on-dashboard-ui[m
  [31mremotes/origin/sk/bugfix-quote-neg-words[m
  [31mremotes/origin/sk/bugfix-rback-for-tracking-ids[m
  [31mremotes/origin/sk/bugfix-recommendations-in-search-UI[m
  [31mremotes/origin/sk/bugfix-recommendations-tag-set-string-instead-of-array[m
  [31mremotes/origin/sk/bugfix-redis-brpop-timeout[m
  [31mremotes/origin/sk/bugfix-redoc[m
  [31mremotes/origin/sk/bugfix-redoc-chunk-group-tracking-id[m
  [31mremotes/origin/sk/bugfix-redoc-get-events-data[m
  [31mremotes/origin/sk/bugfix-remove-unneeded-env[m
  [31mremotes/origin/sk/bugfix-requirementstxt[m
  [31mremotes/origin/sk/bugfix-rerank-truncate[m
  [31mremotes/origin/sk/bugfix-search[m
  [31mremotes/origin/sk/bugfix-search-build[m
  [31mremotes/origin/sk/bugfix-search-replace-error[m
  [31mremotes/origin/sk/bugfix-search-ui-location-display[m
  [31mremotes/origin/sk/bugfix-sparse-encoding-special-chars[m
  [31mremotes/origin/sk/bugfix-stripe-routes[m
  [31mremotes/origin/sk/bugfix-timeout[m
  [31mremotes/origin/sk/bugfix-too-many-batched-embeddings[m
  [31mremotes/origin/sk/bugfix-truncate-jina-hosted[m
  [31mremotes/origin/sk/bugfix-update[m
  [31mremotes/origin/sk/bugfix-update-group-tracking-id[m
  [31mremotes/origin/sk/bugfix-update-user-route[m
  [31mremotes/origin/sk/capture-sentry-error-for-failed-to-insert-chunk_metadata[m
  [31mremotes/origin/sk/change-AF-to-TR-prefix[m
  [31mremotes/origin/sk/change-stripe-redirect-link[m
  [31mremotes/origin/sk/checkpoint-to-restore-main[m
  [31mremotes/origin/sk/cleanup-add-rerank-to-autocomplete[m
  [31mremotes/origin/sk/cleanup-api-schema[m
  [31mremotes/origin/sk/cleanup-correct-unique-dataset-id-tag-constraint[m
  [31mremotes/origin/sk/cleanup-dont-fetch-extra-fields-for-group-recommendations-slim-chunks[m
  [31mremotes/origin/sk/cleanup-navbar[m
  [31mremotes/origin/sk/cleanup-remove-normal-chat-button[m
  [31mremotes/origin/sk/cleanup-remove-pg-trgm-migration-for-yuga[m
  [31mremotes/origin/sk/cleanup-remove-qdrant-conn-hashmap[m
  [31mremotes/origin/sk/cleanup-use-same-tracking-id-logic-for-chunks-as-groups[m
  [31mremotes/origin/sk/cleanup-use-slim-chunk-on-pg-level-for-all-search-and-rec-routes[m
  [31mremotes/origin/sk/content-rename-arguflow-to-trieve[m
  [31mremotes/origin/sk/convert-chunker-to-rust[m
  [31mremotes/origin/sk/convert-server-python-to-rust[m
  [31mremotes/origin/sk/create-stripe-checkout-link[m
  [31mremotes/origin/sk/create-stripe-customer-on-create-user[m
  [31mremotes/origin/sk/default-no-dups[m
  [31mremotes/origin/sk/documentation-get-user-files[m
  [31mremotes/origin/sk/documentation-update-to-remove-shipped-soons[m
  [31mremotes/origin/sk/draft-bulk-insert-from-micro[m
  [31mremotes/origin/sk/error-loading-org-user-count[m
  [31mremotes/origin/sk/feature-add-error-messages-for-notracking-ids-or-group-tracking-ids[m
  [31mremotes/origin/sk/feature-add-request-params-fetch-events[m
  [31mremotes/origin/sk/feature-add-support-for-512-dim[m
  [31mremotes/origin/sk/feature-allow-for-increased-params-for-chat[m
  [31mremotes/origin/sk/feature-filters-modal[m
  [31mremotes/origin/sk/feature-group-recommendations-ui[m
  [31mremotes/origin/sk/feature-replaceable-envs-from-window-search-chat[m
  [31mremotes/origin/sk/feature-require-admin-for-all-message-routes[m
  [31mremotes/origin/sk/feature-return-accurate-id-for-create-file[m
  [31mremotes/origin/sk/feature-return-complete-group-instead-of-slim-group[m
  [31mremotes/origin/sk/feature-show-location-on-search-chunks[m
  [31mremotes/origin/sk/feature-unlimited-plan[m
  [31mremotes/origin/sk/file-delims-v2[m
  [31mremotes/origin/sk/fix-groups-for-search-ui[m
  [31mremotes/origin/sk/fix-ingestion-format-issue[m
  [31mremotes/origin/sk/fix-js-ts-features-prettier[m
  [31mremotes/origin/sk/fix-latency-on-groups-for-dataset[m
  [31mremotes/origin/sk/fix-limit-bug[m
  [31mremotes/origin/sk/fix-missing-users[m
  [31mremotes/origin/sk/fix-openapi-spec[m
  [31mremotes/origin/sk/fix-param-name-for-get-collections-route[m
  [31mremotes/origin/sk/fix-redoc[m
  [31mremotes/origin/sk/fix-scoped-api-keys[m
  [31mremotes/origin/sk/fix-stripe-cancel[m
  [31mremotes/origin/sk/fix-stripe-checkout-bug[m
  [31mremotes/origin/sk/get-all-users-orgs[m
  [31mremotes/origin/sk/group-search-pagination[m
  [31mremotes/origin/sk/highlight-ip[m
  [31mremotes/origin/sk/hotfix-expect-crash-ingestion-worker[m
  [31mremotes/origin/sk/increase-file-size-column-size[m
  [31mremotes/origin/sk/jsonb-prefilter-toggle[m
  [31mremotes/origin/sk/limit-embedding-context-window-size[m
  [31mremotes/origin/sk/limit-implementation[m
  [31mremotes/origin/sk/make-quote-negated-words-default-off[m
  [31mremotes/origin/sk/make-search-ui-url-configurable[m
  [31mremotes/origin/sk/make-weight-decimal-in-ui[m
  [31mremotes/origin/sk/openapi-request-param-docs-pt2[m
  [31mremotes/origin/sk/openapi-request-param-docs-pt3[m
  [31mremotes/origin/sk/optimization-remove-tx-from-insert-chunk-metadata[m
  [31mremotes/origin/sk/optional-streaming[m
  [31mremotes/origin/sk/optional-streaming-for-topic-messages[m
  [31mremotes/origin/sk/organization-auth[m
  [31mremotes/origin/sk/organization-config[m
  [31mremotes/origin/sk/patchfix-window-extension-for-space-delimiter[m
  [31mremotes/origin/sk/payload-indices-env-flag[m
  [31mremotes/origin/sk/plan-limits[m
  [31mremotes/origin/sk/pre-empt-check-for-dup-issue[m
  [31mremotes/origin/sk/prevent-dup-tracking-id-error[m
  [31mremotes/origin/sk/qdrant-multi-tag-set[m
  [31mremotes/origin/sk/readme-update[m
  [31mremotes/origin/sk/refactor-search-enum-to-string[m
  [31mremotes/origin/sk/remove-astro[m
  [31mremotes/origin/sk/remove-brpop-lpush-tx[m
  [31mremotes/origin/sk/remove-card-count-route[m
  [31mremotes/origin/sk/remove-cookie-from-security-addon[m
  [31mremotes/origin/sk/remove-model-from-outdated-routes-on-req-payload[m
  [31mremotes/origin/sk/remove-org-configuration-col[m
  [31mremotes/origin/sk/remove-private[m
  [31mremotes/origin/sk/remove-transaction-from-insert-chunk-metadata[m
  [31mremotes/origin/sk/rename-card-to-chunk[m
  [31mremotes/origin/sk/revert[m
  [31mremotes/origin/sk/search-type-message-completion[m
  [31mremotes/origin/sk/show-dups-on-search[m
  [31mremotes/origin/sk/smtp-over-sendgrid[m
  [31mremotes/origin/sk/speed-up-pg-scroll[m
  [31mremotes/origin/sk/stripe-webhook-bl[m
  [31mremotes/origin/sk/styling-fix-overflow-on-selector[m
  [31mremotes/origin/sk/styling-min-w-on-group-search[m
  [31mremotes/origin/sk/styling-update-dashboard[m
  [31mremotes/origin/sk/tantivy-with-multiple-indices[m
  [31mremotes/origin/sk/upate-qdrant-filters-to-text-match[m
  [31mremotes/origin/sk/update-default-embedding-model[m
  [31mremotes/origin/sk/update-deps[m
  [31mremotes/origin/sk/update-deps-05-14[m
  [31mremotes/origin/sk/update-docs-version[m
  [31mremotes/origin/sk/update-highlight-docs[m
  [31mremotes/origin/sk/update-image-integration[m
  [31mremotes/origin/sk/update-openai-dive[m
  [31mremotes/origin/sk/update-reqs-text[m
  [31mremotes/origin/sk/upsert-on-tracking-id[m
  [31mremotes/origin/sk/use-org-id-for-s3-images[m
  [31mremotes/origin/skeptrunedev-patch-1[m
  [31mremotes/origin/skeptrunedev-patch-2[m
  [31mremotes/origin/tf/add-dashboard-container[m
  [31mremotes/origin/tf/add-dockerfiles[m
  [31mremotes/origin/tf/bake-keycloak[m
  [31mremotes/origin/tf/chat-search-containers[m
  [31mremotes/origin/tf/compose-up-needs-embeddings[m
  [31mremotes/origin/tf/docker-ci[m
  [31mremotes/origin/tf/test-window-env[m
  [31mremotes/origin/trieve-experiment-fork[m
  [31mremotes/origin/vs/add-refresh-btn-chunk-count[m
  [31mremotes/origin/vs/metadata-values-show-up-as-object-object[m
  [31mremotes/origin/vs/remove-references-to-$envs-clientdatasetconfiguration[m
  [31mremotes/origin/vs/use-futures-join-with-multiple-reranker-calls[m
  [31mremotes/origin/window-fix[m
  [31mremotes/origin/window-fix-final-pls[m
