apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-worker
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: worker
          image: worker
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: trieve-db-cluster-app
                  key: uri
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trieve-qdrant-qdrant-apikey
                  key: api-key
          envFrom:
            - configMapRef:
                name: trieve-server-config
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: "1"
              memory: 200Mi
