apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-server
spec:
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: "1"
          image: trieve/server
          ports:
            - containerPort: 8090
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: trieve-postgresql-server-app
                  key: uri
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trieve-qdrant-qdrant-apikey
                  key: api-key
          envFrom:
            - configMapRef:
                name: trieve-server-config
