# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.13.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.create_schema_req_payload import CreateSchemaReqPayload

class TestCreateSchemaReqPayload(unittest.TestCase):
    """CreateSchemaReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSchemaReqPayload:
        """Test CreateSchemaReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSchemaReqPayload`
        """
        model = CreateSchemaReqPayload()
        if include_optional:
            return CreateSchemaReqPayload(
                include_images = True,
                model = '',
                prompt = '',
                tag_enum = [
                    ''
                    ]
            )
        else:
            return CreateSchemaReqPayload(
                prompt = '',
        )
        """

    def testCreateSchemaReqPayload(self):
        """Test CreateSchemaReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
