# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.12.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.event_types_filter import EventTypesFilter

class TestEventTypesFilter(unittest.TestCase):
    """EventTypesFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventTypesFilter(self):
        """Test EventTypesFilter"""
        # inst = EventTypesFilter()

if __name__ == '__main__':
    unittest.main()
