# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.search_response_body import SearchResponseBody

class TestSearchResponseBody(unittest.TestCase):
    """SearchResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchResponseBody:
        """Test SearchResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchResponseBody`
        """
        model = SearchResponseBody()
        if include_optional:
            return SearchResponseBody(
                chunks = [
                    {"chunk":{"chunk_html":"<p>Some HTML content</p>","content":"Some content","id":"d290f1ee-6c54-4b01-90e6-d701748f0851","link":"https://example.com","metadata":{"key1":"value1","key2":"value2"},"time_stamp":"2021-01-01 00:00:00.000","weight":0.5},"highlights":["highlight is two tokens: high, light","whereas hello is only one token: hello"],"score":0.5}
                    ],
                corrected_query = '',
                id = '',
                total_pages = 56
            )
        else:
            return SearchResponseBody(
                chunks = [
                    {"chunk":{"chunk_html":"<p>Some HTML content</p>","content":"Some content","id":"d290f1ee-6c54-4b01-90e6-d701748f0851","link":"https://example.com","metadata":{"key1":"value1","key2":"value2"},"time_stamp":"2021-01-01 00:00:00.000","weight":0.5},"highlights":["highlight is two tokens: high, light","whereas hello is only one token: hello"],"score":0.5}
                    ],
                id = '',
                total_pages = 56,
        )
        """

    def testSearchResponseBody(self):
        """Test SearchResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
