# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.recommendation_analytics import RecommendationAnalytics

class TestRecommendationAnalytics(unittest.TestCase):
    """RecommendationAnalytics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendationAnalytics:
        """Test RecommendationAnalytics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendationAnalytics`
        """
        model = RecommendationAnalytics()
        if include_optional:
            return RecommendationAnalytics(
                filter = trieve_py_client.models.recommendation_analytics_filter.RecommendationAnalyticsFilter(
                    date_range = null, 
                    recommendation_type = null, ),
                page = 0,
                threshold = 1.337,
                type = 'low_confidence_recommendations',
                sort_by = 'created_at',
                sort_order = 'desc'
            )
        else:
            return RecommendationAnalytics(
                type = 'low_confidence_recommendations',
        )
        """

    def testRecommendationAnalytics(self):
        """Test RecommendationAnalytics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
