# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.highlight_options import HighlightOptions

class TestHighlightOptions(unittest.TestCase):
    """HighlightOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HighlightOptions:
        """Test HighlightOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HighlightOptions`
        """
        model = HighlightOptions()
        if include_optional:
            return HighlightOptions(
                highlight_delimiters = [
                    ''
                    ],
                highlight_max_length = 0,
                highlight_max_num = 0,
                highlight_results = True,
                highlight_strategy = 'exactmatch',
                highlight_threshold = 1.337,
                highlight_window = 0
            )
        else:
            return HighlightOptions(
        )
        """

    def testHighlightOptions(self):
        """Test HighlightOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
