# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.upload_file_req_payload import UploadFileReqPayload

class TestUploadFileReqPayload(unittest.TestCase):
    """UploadFileReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadFileReqPayload:
        """Test UploadFileReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadFileReqPayload`
        """
        model = UploadFileReqPayload()
        if include_optional:
            return UploadFileReqPayload(
                base64_file = '',
                create_chunks = True,
                description = '',
                file_name = '',
                group_tracking_id = '',
                link = '',
                metadata = None,
                rebalance_chunks = True,
                split_delimiters = [
                    ''
                    ],
                tag_set = [
                    ''
                    ],
                target_splits_per_chunk = 0,
                time_stamp = ''
            )
        else:
            return UploadFileReqPayload(
                base64_file = '',
                file_name = '',
        )
        """

    def testUploadFileReqPayload(self):
        """Test UploadFileReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
