# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.13.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.scrape_options_one_of2 import ScrapeOptionsOneOf2

class TestScrapeOptionsOneOf2(unittest.TestCase):
    """ScrapeOptionsOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScrapeOptionsOneOf2:
        """Test ScrapeOptionsOneOf2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScrapeOptionsOneOf2`
        """
        model = ScrapeOptionsOneOf2()
        if include_optional:
            return ScrapeOptionsOneOf2(
                type = 'youtube'
            )
        else:
            return ScrapeOptionsOneOf2(
                type = 'youtube',
        )
        """

    def testScrapeOptionsOneOf2(self):
        """Test ScrapeOptionsOneOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
