# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.update_group_by_tracking_id_req_payload import UpdateGroupByTrackingIDReqPayload

class TestUpdateGroupByTrackingIDReqPayload(unittest.TestCase):
    """UpdateGroupByTrackingIDReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGroupByTrackingIDReqPayload:
        """Test UpdateGroupByTrackingIDReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGroupByTrackingIDReqPayload`
        """
        model = UpdateGroupByTrackingIDReqPayload()
        if include_optional:
            return UpdateGroupByTrackingIDReqPayload(
                description = '',
                metadata = None,
                name = '',
                tag_set = [
                    ''
                    ],
                tracking_id = ''
            )
        else:
            return UpdateGroupByTrackingIDReqPayload(
                tracking_id = '',
        )
        """

    def testUpdateGroupByTrackingIDReqPayload(self):
        """Test UpdateGroupByTrackingIDReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
