# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.content_chunk_metadata import ContentChunkMetadata

class TestContentChunkMetadata(unittest.TestCase):
    """ContentChunkMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentChunkMetadata:
        """Test ContentChunkMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentChunkMetadata`
        """
        model = ContentChunkMetadata()
        if include_optional:
            return ContentChunkMetadata(
                chunk_html = '',
                id = '',
                image_urls = [
                    ''
                    ],
                num_value = 1.337,
                time_stamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tracking_id = '',
                weight = 1.337
            )
        else:
            return ContentChunkMetadata(
                id = '',
                weight = 1.337,
        )
        """

    def testContentChunkMetadata(self):
        """Test ContentChunkMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
