# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.api.invitation_api import InvitationApi


class TestInvitationApi(unittest.TestCase):
    """InvitationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvitationApi()

    def tearDown(self) -> None:
        pass

    def test_post_invitation(self) -> None:
        """Test case for post_invitation

        Send Invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
