# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.count_chunks_req_payload import CountChunksReqPayload

class TestCountChunksReqPayload(unittest.TestCase):
    """CountChunksReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountChunksReqPayload:
        """Test CountChunksReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountChunksReqPayload`
        """
        model = CountChunksReqPayload()
        if include_optional:
            return CountChunksReqPayload(
                filters = {"must":[{"field":"tag_set","match_all":["A","B"]},{"field":"num_value","range":{"gte":10,"lte":25}}]},
                limit = 0,
                query = None,
                score_threshold = 1.337,
                search_type = 'fulltext',
                use_quote_negated_terms = True
            )
        else:
            return CountChunksReqPayload(
                query = None,
                search_type = 'fulltext',
        )
        """

    def testCountChunksReqPayload(self):
        """Test CountChunksReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
