# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.9
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.crawl_options import CrawlOptions

class TestCrawlOptions(unittest.TestCase):
    """CrawlOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrawlOptions:
        """Test CrawlOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrawlOptions`
        """
        model = CrawlOptions()
        if include_optional:
            return CrawlOptions(
                exclude_paths = [
                    ''
                    ],
                exclude_tags = [
                    ''
                    ],
                include_paths = [
                    ''
                    ],
                include_tags = [
                    ''
                    ],
                interval = 'daily',
                limit = 56,
                max_depth = 56,
                site_url = ''
            )
        else:
            return CrawlOptions(
        )
        """

    def testCrawlOptions(self):
        """Test CrawlOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
