# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.search_query_event import SearchQueryEvent

class TestSearchQueryEvent(unittest.TestCase):
    """SearchQueryEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchQueryEvent:
        """Test SearchQueryEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchQueryEvent`
        """
        model = SearchQueryEvent()
        if include_optional:
            return SearchQueryEvent(
                created_at = '',
                dataset_id = '',
                id = '',
                latency = 1.337,
                query = '',
                query_rating = '',
                request_params = None,
                results = [
                    null
                    ],
                search_type = '',
                top_score = 1.337,
                user_id = ''
            )
        else:
            return SearchQueryEvent(
                created_at = '',
                dataset_id = '',
                id = '',
                latency = 1.337,
                query = '',
                query_rating = '',
                request_params = None,
                results = [
                    null
                    ],
                search_type = '',
                top_score = 1.337,
                user_id = '',
        )
        """

    def testSearchQueryEvent(self):
        """Test SearchQueryEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
