# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.query_count_response import QueryCountResponse

class TestQueryCountResponse(unittest.TestCase):
    """QueryCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryCountResponse:
        """Test QueryCountResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryCountResponse`
        """
        model = QueryCountResponse()
        if include_optional:
            return QueryCountResponse(
                total_queries = [
                    {"search_count":8,"search_type":"search"}
                    ]
            )
        else:
            return QueryCountResponse(
                total_queries = [
                    {"search_count":8,"search_type":"search"}
                    ],
        )
        """

    def testQueryCountResponse(self):
        """Test QueryCountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
