# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.field_condition import FieldCondition

class TestFieldCondition(unittest.TestCase):
    """FieldCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldCondition:
        """Test FieldCondition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldCondition`
        """
        model = FieldCondition()
        if include_optional:
            return FieldCondition(
                date_range = {"gt":"2021-01-01 00:00:00.000","gte":"2021-01-01 00:00:00.000","lt":"2021-01-01 00:00:00.000","lte":"2021-01-01 00:00:00.000"},
                field = '',
                geo_bounding_box = trieve_py_client.models.location_bounding_box.LocationBoundingBox(
                    bottom_right = trieve_py_client.models.geo_info.GeoInfo(
                        lat = null, 
                        lon = null, ), 
                    top_left = trieve_py_client.models.geo_info.GeoInfo(
                        lat = null, 
                        lon = null, ), ),
                geo_polygon = trieve_py_client.models.location_polygon.LocationPolygon(
                    exterior = [
                        trieve_py_client.models.geo_info.GeoInfo(
                            lat = null, 
                            lon = null, )
                        ], 
                    interior = [
                        [
                            trieve_py_client.models.geo_info.GeoInfo(
                                lat = null, 
                                lon = null, )
                            ]
                        ], ),
                geo_radius = trieve_py_client.models.location_radius.LocationRadius(
                    center = trieve_py_client.models.geo_info.GeoInfo(
                        lat = null, 
                        lon = null, ), 
                    radius = 1.337, ),
                match_all = [
                    null
                    ],
                match_any = [
                    null
                    ],
                range = {"gt":0.0,"gte":0.0,"lt":1.0,"lte":1.0}
            )
        else:
            return FieldCondition(
                field = '',
        )
        """

    def testFieldCondition(self):
        """Test FieldCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
