# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.recommend_chunks_request import RecommendChunksRequest

class TestRecommendChunksRequest(unittest.TestCase):
    """RecommendChunksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendChunksRequest:
        """Test RecommendChunksRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendChunksRequest`
        """
        model = RecommendChunksRequest()
        if include_optional:
            return RecommendChunksRequest(
                filters = {"must":[{"field":"tag_set","match_all":["A","B"]},{"field":"num_value","range":{"gte":10,"lte":25}}]},
                limit = 0,
                negative_chunk_ids = [
                    ''
                    ],
                negative_tracking_ids = [
                    ''
                    ],
                positive_chunk_ids = [
                    ''
                    ],
                positive_tracking_ids = [
                    ''
                    ],
                recommend_type = 'semantic',
                slim_chunks = True,
                strategy = 'average_vector',
                user_id = ''
            )
        else:
            return RecommendChunksRequest(
        )
        """

    def testRecommendChunksRequest(self):
        """Test RecommendChunksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
