# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.search_over_groups_req_payload import SearchOverGroupsReqPayload

class TestSearchOverGroupsReqPayload(unittest.TestCase):
    """SearchOverGroupsReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchOverGroupsReqPayload:
        """Test SearchOverGroupsReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchOverGroupsReqPayload`
        """
        model = SearchOverGroupsReqPayload()
        if include_optional:
            return SearchOverGroupsReqPayload(
                filters = {"must":[{"field":"tag_set","match_all":["A","B"]},{"field":"num_value","range":{"gte":10,"lte":25}}]},
                get_total_pages = True,
                group_size = 0,
                highlight_options = trieve_py_client.models.highlight_options.HighlightOptions(
                    highlight_delimiters = [
                        ''
                        ], 
                    highlight_max_length = 0, 
                    highlight_max_num = 0, 
                    highlight_results = True, 
                    highlight_strategy = null, 
                    highlight_threshold = 1.337, 
                    highlight_window = 0, ),
                page = 0,
                page_size = 0,
                query = None,
                remove_stop_words = True,
                score_threshold = 1.337,
                search_type = 'fulltext',
                slim_chunks = True,
                typo_options = trieve_py_client.models.typo_options.TypoOptions(
                    correct_typos = True, 
                    disable_on_word = [
                        ''
                        ], 
                    one_typo_word_range = null, 
                    prioritize_domain_specifc_words = True, 
                    two_typo_word_range = null, ),
                use_quote_negated_terms = True,
                user_id = ''
            )
        else:
            return SearchOverGroupsReqPayload(
                query = None,
                search_type = 'fulltext',
        )
        """

    def testSearchOverGroupsReqPayload(self):
        """Test SearchOverGroupsReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
