# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.rag_analytics_filter import RAGAnalyticsFilter

class TestRAGAnalyticsFilter(unittest.TestCase):
    """RAGAnalyticsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RAGAnalyticsFilter:
        """Test RAGAnalyticsFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RAGAnalyticsFilter`
        """
        model = RAGAnalyticsFilter()
        if include_optional:
            return RAGAnalyticsFilter(
                date_range = {"gt":"2021-01-01 00:00:00.000","gte":"2021-01-01 00:00:00.000","lt":"2021-01-01 00:00:00.000","lte":"2021-01-01 00:00:00.000"},
                rag_type = 'chosen_chunks'
            )
        else:
            return RAGAnalyticsFilter(
        )
        """

    def testRAGAnalyticsFilter(self):
        """Test RAGAnalyticsFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
