# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.latency_graph import LatencyGraph

class TestLatencyGraph(unittest.TestCase):
    """LatencyGraph unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LatencyGraph:
        """Test LatencyGraph
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LatencyGraph`
        """
        model = LatencyGraph()
        if include_optional:
            return LatencyGraph(
                filter = trieve_py_client.models.search_analytics_filter.SearchAnalyticsFilter(
                    date_range = null, 
                    search_method = null, 
                    search_type = null, ),
                granularity = 'minute',
                type = 'latency_graph'
            )
        else:
            return LatencyGraph(
                type = 'latency_graph',
        )
        """

    def testLatencyGraph(self):
        """Test LatencyGraph"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
