# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_get_cluster_analytics(self) -> None:
        """Test case for get_cluster_analytics

        Get Cluster Analytics
        """
        pass

    def test_get_ctr_analytics(self) -> None:
        """Test case for get_ctr_analytics

        Get CTR Analytics
        """
        pass

    def test_get_rag_analytics(self) -> None:
        """Test case for get_rag_analytics

        Get RAG Analytics
        """
        pass

    def test_get_recommendation_analytics(self) -> None:
        """Test case for get_recommendation_analytics

        Get Recommendation Analytics
        """
        pass

    def test_get_search_analytics(self) -> None:
        """Test case for get_search_analytics

        Get Search Analytics
        """
        pass

    def test_get_top_datasets(self) -> None:
        """Test case for get_top_datasets

        Get Top Datasets
        """
        pass

    def test_send_ctr_data(self) -> None:
        """Test case for send_ctr_data

        Send CTR Data
        """
        pass

    def test_send_event_data(self) -> None:
        """Test case for send_event_data

        Send Event Data
        """
        pass

    def test_set_query_rating(self) -> None:
        """Test case for set_query_rating

        Rate Query
        """
        pass


if __name__ == '__main__':
    unittest.main()
