# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.recommendation_ctr_metrics1 import RecommendationCTRMetrics1

class TestRecommendationCTRMetrics1(unittest.TestCase):
    """RecommendationCTRMetrics1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendationCTRMetrics1:
        """Test RecommendationCTRMetrics1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendationCTRMetrics1`
        """
        model = RecommendationCTRMetrics1()
        if include_optional:
            return RecommendationCTRMetrics1(
                filter = trieve_py_client.models.recommendation_analytics_filter.RecommendationAnalyticsFilter(
                    date_range = null, 
                    recommendation_type = null, ),
                type = 'recommendation_ctr_metrics'
            )
        else:
            return RecommendationCTRMetrics1(
                type = 'recommendation_ctr_metrics',
        )
        """

    def testRecommendationCTRMetrics1(self):
        """Test RecommendationCTRMetrics1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
