# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.13.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.create_presigned_url_for_csv_jsonl_req_payload import CreatePresignedUrlForCsvJsonlReqPayload

class TestCreatePresignedUrlForCsvJsonlReqPayload(unittest.TestCase):
    """CreatePresignedUrlForCsvJsonlReqPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePresignedUrlForCsvJsonlReqPayload:
        """Test CreatePresignedUrlForCsvJsonlReqPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePresignedUrlForCsvJsonlReqPayload`
        """
        model = CreatePresignedUrlForCsvJsonlReqPayload()
        if include_optional:
            return CreatePresignedUrlForCsvJsonlReqPayload(
                description = '',
                file_name = '',
                fulltext_boost_factor = 1.337,
                group_tracking_id = '',
                link = '',
                mappings = [
                    trieve_py_client.models.chunk_req_payload_mapping.ChunkReqPayloadMapping(
                        chunk_req_payload_field = 'link', 
                        csv_jsonl_field = '', )
                    ],
                metadata = None,
                semantic_boost_factor = 1.337,
                tag_set = [
                    ''
                    ],
                time_stamp = '',
                upsert_by_tracking_id = True
            )
        else:
            return CreatePresignedUrlForCsvJsonlReqPayload(
                file_name = '',
        )
        """

    def testCreatePresignedUrlForCsvJsonlReqPayload(self):
        """Test CreatePresignedUrlForCsvJsonlReqPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
