{
  "openapi": "3.0.3",
  "info": {
    "title": "Trieve API",
    "description": "Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.",
    "contact": {
      "name": "Trieve Team",
      "url": "https://trieve.ai",
      "email": "developers@trieve.ai"
    },
    "license": {
      "name": "BSL",
      "url": "https://github.com/devflowinc/trieve/blob/main/LICENSE.txt"
    },
    "version": "0.13.0"
  },
  "servers": [
    {
      "url": "https://api.trieve.ai",
      "description": "Production server"
    },
    {
      "url": "http://localhost:8090",
      "description": "Local development server"
    }
  ],
  "paths": {
    "/api/analytics": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Analytics",
        "description": "This route allows you to view the analytics for a dataset using a structured query.",
        "operationId": "get_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/ctr": {
      "put": {
        "tags": [
          "Analytics"
        ],
        "summary": "Send CTR Data",
        "description": "This route allows you to send clickstream data to the system. Clickstream data is used to fine-tune the re-ranking of search results and recommendations.",
        "operationId": "send_ctr_data",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/events": {
      "put": {
        "tags": [
          "Analytics"
        ],
        "summary": "Send User Event Data",
        "description": "This route allows you to send user event data to the system.",
        "operationId": "send_event_data",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/events/all": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get All User Events",
        "description": "This route allows you to view all user events.",
        "operationId": "get_all_events",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/events/component": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Component Analytics",
        "description": "This route allows you to view the component analytics for a dataset.",
        "operationId": "get_component_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/events/ctr": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get CTR Analytics",
        "description": "This route allows you to view the CTR analytics for a dataset.",
        "operationId": "get_ctr_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/events/{event_id}": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get User Event By ID",
        "description": "This route allows you to view an user event by its ID. You can pass in any type of event and get the details for that event.",
        "operationId": "get_event_by_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/rag": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get RAG Analytics",
        "description": "This route allows you to view the RAG analytics for a dataset.",
        "operationId": "get_rag_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Analytics"
        ],
        "summary": "Rate RAG",
        "description": "This route allows you to Rate a RAG query.",
        "operationId": "set_rag_query_rating",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/recommendations": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Recommendation Analytics",
        "description": "This route allows you to view the recommendation analytics for a dataset.",
        "operationId": "get_recommendation_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/search": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Search Analytics",
        "description": "This route allows you to view the search analytics for a dataset.",
        "operationId": "get_search_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Analytics"
        ],
        "summary": "Rate Search",
        "description": "This route allows you to Rate a search query.",
        "operationId": "set_search_query_rating",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/search/cluster": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Cluster Analytics",
        "description": "This route allows you to view the cluster analytics for a dataset.",
        "operationId": "get_cluster_analytics",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/analytics/top": {
      "post": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get Top Datasets",
        "description": "This route allows you to view the top datasets for a given type.",
        "operationId": "get_top_datasets",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/auth": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Login",
        "description": "This will redirect you to the OAuth provider for authentication with email/pass, SSO, Google, Github, etc.",
        "operationId": "login"
      },
      "delete": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout",
        "description": "Invalidate your current auth credential stored typically stored in a cookie. This does not invalidate your API key.",
        "operationId": "logout"
      }
    },
    "/api/auth/callback": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "OpenID Connect callback",
        "description": "This is the callback route for the OAuth provider, it should not be called directly. Redirects to browser with set-cookie header.",
        "operationId": "oidc_callback"
      }
    },
    "/api/auth/create_api_only_user": {
      "post": {
        "tags": [
          "Auth"
        ],
        "operationId": "create_api_only_user",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/auth/me": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Get Me",
        "description": "Get the user corresponding to your current auth credentials.",
        "operationId": "get_me",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Create or Upsert Chunk or Chunks",
        "description": "Create new chunk(s). If the chunk has the same tracking_id as an existing chunk, the request will fail. Once a chunk is created, it can be searched for using the search endpoint.\nIf uploading in bulk, the maximum amount of chunks that can be uploaded at once is 120 chunks. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "create_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Chunk"
        ],
        "summary": "Update Chunk",
        "description": "Update a chunk. If you try to change the tracking_id of the chunk to have the same tracking_id as an existing chunk, the request will fail. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "update_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk"
        ],
        "summary": "Bulk Delete Chunks",
        "description": "Delete multiple chunks using a filter. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "bulk_delete_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/autocomplete": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Autocomplete",
        "description": "This route provides the primary autocomplete functionality for the API. This prioritize prefix matching with semantic or full-text search.",
        "operationId": "autocomplete",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/count": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Count chunks above threshold",
        "description": "This route can be used to determine the number of chunk results that match a search query including score threshold and filters. It may be high latency for large limits. There is a dataset configuration imposed restriction on the maximum limit value (default 10,000) which is used to prevent DDOS attacks. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "count_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/generate": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "RAG on Specified Chunks",
        "description": "This endpoint exists as an alternative to the topic+message resource pattern where our Trieve handles chat memory. With this endpoint, the user is responsible for providing the context window and the prompt and the conversation is ephemeral.",
        "operationId": "generate_off_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/recommend": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Get Recommended Chunks",
        "description": "Get recommendations of chunks similar to the positive samples in the request and dissimilar to the negative.",
        "operationId": "get_recommended_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/search": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Search",
        "description": "This route provides the primary search functionality for the API. It can be used to search for chunks by semantic similarity, full-text similarity, or a combination of both. Results' `chunk_html` values will be modified with `<mark><b>` or custom specified tags for sub-sentence highlighting.",
        "operationId": "search_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/split": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Split HTML Content into Chunks",
        "description": "This endpoint receives a single html string and splits it into chunks based on the headings and\nbody content. The headings are split based on heading html tags. chunk_html has a maximum size\nof 256Kb.",
        "operationId": "split_html_content"
      }
    },
    "/api/chunk/suggestions": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Generate suggested queries",
        "description": "This endpoint will generate 3 suggested queries based off a hybrid search using RAG with the query provided in the request body and return them as a JSON object.",
        "operationId": "get_suggested_queries",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/tracking_id/update": {
      "put": {
        "tags": [
          "Chunk"
        ],
        "summary": "Update Chunk By Tracking Id",
        "description": "Update a chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "update_chunk_by_tracking_id",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/tracking_id/{tracking_id}": {
      "get": {
        "tags": [
          "Chunk"
        ],
        "summary": "Get Chunk By Tracking Id",
        "description": "Get a singular chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use your own id as the primary reference for a chunk.",
        "operationId": "get_chunk_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk"
        ],
        "summary": "Delete Chunk By Tracking Id",
        "description": "Delete a chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_chunk_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/{chunk_id}": {
      "get": {
        "tags": [
          "Chunk"
        ],
        "summary": "Get Chunk By Id",
        "description": "Get a singular chunk by id.",
        "operationId": "get_chunk_by_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk"
        ],
        "summary": "Delete Chunk",
        "description": "Delete a chunk by its id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Create or Upsert Group or Groups",
        "description": "Create new chunk_group(s). This is a way to group chunks together. If you try to create a chunk_group with the same tracking_id as an existing chunk_group, this operation will fail. Only 1000 chunk groups can be created at a time. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "create_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Update Group",
        "description": "Update a chunk_group. One of group_id or tracking_id must be provided. If you try to change the tracking_id to one that already exists, this operation will fail. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "update_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/chunk/{group_id}": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Add Chunk to Group",
        "description": "Route to add a chunk to a group. One of chunk_id or chunk_tracking_id must be provided. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "add_chunk_to_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Remove Chunk from Group",
        "description": "Route to remove a chunk from a group. Auth'ed user or api key must be an admin or owner of the dataset's organization to remove a chunk from a group.",
        "operationId": "remove_chunk_from_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/chunks": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Groups for Chunks",
        "description": "Route to get the groups that a chunk is in.",
        "operationId": "get_groups_for_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/count": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Count Chunks in a Group",
        "description": "Route to get the number of chunks that is in a group",
        "operationId": "count_group_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/group_oriented_autocomplete": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Autocomplete Search Over Groups",
        "description": "This route provides the primary autocomplete functionality for the API. This prioritize prefix matching with semantic or full-text search.",
        "operationId": "autocomplete_search_over_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/group_oriented_search": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Search Over Groups",
        "description": "This route allows you to get groups as results instead of chunks. Each group returned will have the matching chunks sorted by similarity within the group. This is useful for when you want to get groups of chunks which are similar to the search query. If choosing hybrid search, the top chunk of each group will be re-ranked using scores from a cross encoder model. Compatible with semantic, fulltext, or hybrid search modes.",
        "operationId": "search_over_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/recommend": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Recommended Groups",
        "description": "Route to get recommended groups. This route will return groups which are similar to the groups in the request body. You must provide at least one positive group id or group tracking id.",
        "operationId": "get_recommended_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/search": {
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Search Within Group",
        "description": "This route allows you to search only within a group. This is useful for when you only want search results to contain chunks which are members of a specific group. If choosing hybrid search, the results will be re-ranked using scores from a cross encoder model.",
        "operationId": "search_within_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/tracking_id/{group_tracking_id}/{page}": {
      "get": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Chunks in Group by Tracking ID",
        "description": "Route to get all chunks for a group. The response is paginated, with each page containing 10 chunks. Support for custom page size is coming soon. Page is 1-indexed.",
        "operationId": "get_chunks_in_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/tracking_id/{tracking_id}": {
      "get": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Group by Tracking ID",
        "description": "Fetch the group with the given tracking id.\nget_group_by_tracking_id",
        "operationId": "get_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Add Chunk to Group by Tracking ID",
        "description": "Route to add a chunk to a group by tracking id. One of chunk_id or chunk_tracking_id must be provided. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "add_chunk_to_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Delete Group by Tracking ID",
        "description": "Delete a chunk_group with the given tracking id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/{group_id}": {
      "get": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Group",
        "description": "Fetch the group with the given id.",
        "operationId": "get_chunk_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Delete Group",
        "description": "This will delete a chunk_group. If you set delete_chunks to true, it will also delete the chunks within the group. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/{group_id}/{page}": {
      "get": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Chunks in Group",
        "description": "Route to get all chunks for a group. The response is paginated, with each page containing 10 chunks. Page is 1-indexed.",
        "operationId": "get_chunks_in_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunks": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Get Chunks By Ids",
        "description": "Get multiple chunks by multiple ids.",
        "operationId": "get_chunks_by_ids",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunks/scroll": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Scroll Chunks",
        "description": "Get paginated chunks from your dataset with filters and custom sorting. If sort by is not specified, the results will sort by the id's of the chunks in ascending order. Sort by and offset_chunk_id cannot be used together; if you want to scroll with a sort by then you need to use a must_not filter with the ids you have already seen. There is a limit of 1000 id's in a must_not filter at a time.",
        "operationId": "scroll_dataset_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunks/tracking": {
      "post": {
        "tags": [
          "Chunk"
        ],
        "summary": "Get Chunks By Tracking Ids",
        "description": "Get multiple chunks by ids.",
        "operationId": "get_chunks_by_tracking_ids",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/crawl": {
      "get": {
        "tags": [
          "Crawl"
        ],
        "summary": "Get all crawl requests for a dataset",
        "description": "This endpoint is used to get all crawl requests for a dataset.",
        "operationId": "get_crawl_requests_for_dataset",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Crawl"
        ],
        "summary": "Create a new crawl request",
        "description": "This endpoint is used to create a new crawl request for a dataset. The request payload should contain the crawl options to use for the crawl.",
        "operationId": "create_crawl",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Crawl"
        ],
        "summary": "Update a crawl request",
        "description": "This endpoint is used to update an existing crawl request for a dataset. The request payload should contain the crawl id and the crawl options to update for the crawl.",
        "operationId": "update_crawl_request",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/crawl/{crawl_id}": {
      "delete": {
        "tags": [
          "Crawl"
        ],
        "summary": "Delete a crawl request",
        "description": "This endpoint is used to delete an existing crawl request for a dataset. The request payload should contain the crawl id to delete.",
        "operationId": "delete_crawl_request",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/dataset": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Create Dataset",
        "description": "Dataset will be created in the org specified via the TR-Organization header. Auth'ed user must be an owner of the organization to create a dataset.",
        "operationId": "create_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Dataset"
        ],
        "summary": "Update Dataset by ID or Tracking ID",
        "description": "One of id or tracking_id must be provided. The auth'ed user must be an owner of the organization to update a dataset.",
        "operationId": "update_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/batch_create_datasets": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Batch Create Datasets",
        "description": "Datasets will be created in the org specified via the TR-Organization header. Auth'ed user must be an owner of the organization to create datasets. If a tracking_id is ignored due to it already existing on the org, the response will not contain a dataset with that tracking_id and it can be assumed that a dataset with the missing tracking_id already exists.",
        "operationId": "batch_create_datasets",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/clear/{dataset_id}": {
      "put": {
        "tags": [
          "Dataset"
        ],
        "summary": "Clear Dataset",
        "description": "Removes all chunks, files, and groups from the dataset while retaining the analytics and dataset itself. The auth'ed user must be an owner of the organization to clear a dataset.",
        "operationId": "clear_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/clone": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Clone Dataset",
        "description": "Clones a dataset and creates a new dataset with the same configuration and chunks. The auth'ed user must be an owner of the organization to clone a dataset.",
        "operationId": "clone_dataset"
      }
    },
    "/api/dataset/events": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get events for the dataset",
        "description": "Get events for the dataset specified by the TR-Dataset header.",
        "operationId": "get_events",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/files/{dataset_id}/{page}": {
      "get": {
        "tags": [
          "File"
        ],
        "summary": "Get Files and Group IDs for Dataset",
        "description": "Get all files and their group ids which belong to a given dataset specified by the dataset_id parameter. 10 files and group ids are returned per page. This route may return the same file multiple times if the file is associated with multiple groups.",
        "operationId": "get_dataset_files_and_group_ids_handler",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/get_all_tags": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get All Tags",
        "description": "Scroll through all tags in the dataset and get the number of chunks in the dataset with that tag plus the total number of unique tags for the whole datset.",
        "operationId": "get_all_tags",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/groups/{dataset_id}/{page}": {
      "get": {
        "tags": [
          "Chunk Group"
        ],
        "summary": "Get Groups for Dataset",
        "description": "Fetch the groups which belong to a dataset specified by its id.",
        "operationId": "get_groups_for_dataset",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/organization/{organization_id}": {
      "get": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get Datasets from Organization",
        "description": "Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_datasets_from_organization",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/dataset/pagefind": {
      "get": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get Pagefind Index Url for Dataset",
        "description": "Returns the root URL for your pagefind index, will error if pagefind is not enabled",
        "operationId": "get_pagefind_index_for_dataset",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Dataset"
        ],
        "summary": "Create Pagefind Index for Dataset",
        "description": "Uses pagefind to index the dataset and store the result into a CDN for retrieval. The auth'ed\nuser must be an admin of the organization to create a pagefind index for a dataset.",
        "operationId": "create_pagefind_index_for_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/scroll_files": {
      "get": {
        "tags": [
          "File"
        ],
        "summary": "Scroll Files with Groups",
        "description": "Scroll through the files along with their groups in a dataset. This is useful for paginating through files. The cursor is used to fetch the next page of files. The page size is used to specify how many files to fetch per page. The default page size is 10.",
        "operationId": "get_files_cursor_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/tracking_id/{tracking_id}": {
      "get": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get Dataset by Tracking ID",
        "description": "Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_dataset_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Dataset"
        ],
        "summary": "Delete Dataset by Tracking ID",
        "description": "Auth'ed user must be an owner of the organization to delete a dataset.",
        "operationId": "delete_dataset_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/usage/{dataset_id}": {
      "get": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get Usage By Dataset ID",
        "description": "Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_usage_by_dataset_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/dataset/{dataset_id}": {
      "get": {
        "tags": [
          "Dataset"
        ],
        "summary": "Get Dataset By ID",
        "description": "Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_dataset",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Dataset"
        ],
        "summary": "Delete Dataset",
        "description": "Auth'ed user must be an owner of the organization to delete a dataset.",
        "operationId": "delete_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/etl/create_job": {
      "post": {
        "tags": [
          "Dataset"
        ],
        "summary": "Create ETL Job",
        "description": "This endpoint is used to create a new ETL job for a dataset.",
        "operationId": "create_etl_job",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/experiment": {
      "get": {
        "tags": [
          "Experiment"
        ],
        "summary": "Get Experiments",
        "description": "Get all experiments for a dataset. Auth'ed user must be an owner of the organization to get experiments.",
        "operationId": "get_experiments",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Experiment"
        ],
        "summary": "Create Experiment",
        "description": "Experiment will be created in the dataset specified via the TR-Dataset header. Auth'ed user must be an owner of the organization to create an experiment.",
        "operationId": "create_experiment",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Experiment"
        ],
        "summary": "Update Experiment",
        "description": "Update an experiment. Auth'ed user must be an owner of the organization to update an experiment.",
        "operationId": "update_experiment",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/experiment/ab-test": {
      "post": {
        "tags": [
          "Experiment"
        ],
        "summary": "Ab Test",
        "description": "Get a user's treatment for an experiment. Auth'ed user must be an owner of the organization to get a user's treatment.",
        "operationId": "ab_test",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/experiment/{experiment_id}": {
      "get": {
        "tags": [
          "Experiment"
        ],
        "summary": "Get Experiment by ID",
        "description": "Get an experiment by ID. Auth'ed user must be an owner of the organization to get an experiment.",
        "operationId": "get_experiment",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Experiment"
        ],
        "summary": "Delete Experiment",
        "description": "Delete an experiment. Auth'ed user must be an owner of the organization to delete an experiment.",
        "operationId": "delete_experiment",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/file": {
      "post": {
        "tags": [
          "File"
        ],
        "summary": "Upload File",
        "description": "Upload a file to S3 bucket attached to your dataset. You can select between a naive chunking strategy where the text is extracted with Apache Tika and split into segments with a target number of segments per chunk OR you can use a vision LLM to convert the file to markdown and create chunks per page. You must specifically use a base64url encoding. Auth'ed user must be an admin or owner of the dataset's organization to upload a file.",
        "operationId": "upload_file_handler",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/file/csv_or_jsonl": {
      "post": {
        "tags": [
          "File"
        ],
        "summary": "Create Presigned CSV/JSONL S3 PUT URL",
        "description": "This route is useful for uploading very large CSV or JSONL files. Once you have completed the upload, chunks will be automatically created from the file for each line in the CSV or JSONL file. The chunks will be indexed and searchable. Auth'ed user must be an admin or owner of the dataset's organization to upload a file.",
        "operationId": "create_presigned_url_for_csv_jsonl",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/file/html_page": {
      "post": {
        "tags": [
          "File"
        ],
        "summary": "Upload HTML Page",
        "description": "Chunk HTML by headings and queue for indexing into the specified dataset.",
        "operationId": "upload_html_page"
      }
    },
    "/api/file/{file_id}": {
      "get": {
        "tags": [
          "File"
        ],
        "summary": "Get File with Signed URL",
        "description": "Get all of the information for a file along with a signed s3 url corresponding to the file_id requested such that you can download the file.",
        "operationId": "get_file_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "File"
        ],
        "summary": "Delete File",
        "description": "Delete a file from S3 attached to the server based on its id. This will disassociate chunks from the file, but only delete them all together if you specify delete_chunks to be true. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_file_handler",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/health": {
      "get": {
        "tags": [
          "Health"
        ],
        "summary": "Health Check",
        "description": "Confirmation that the service is healthy and can make embedding vectors",
        "operationId": "health_check"
      }
    },
    "/api/invitation": {
      "post": {
        "tags": [
          "Invitation"
        ],
        "summary": "Send Invitation",
        "description": "Invitations act as a way to invite users to join an organization. After a user is invited, they will automatically be added to the organization with the role specified in the invitation once they set their. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "post_invitation",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/invitation/{invitation_id}": {
      "delete": {
        "tags": [
          "Invitation"
        ],
        "summary": "Delete Invitation",
        "description": "Delete an invitation by id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_invitation",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/invitations/{organization_id}": {
      "get": {
        "tags": [
          "Invitation"
        ],
        "summary": "Get Invitations",
        "description": "Get all invitations for the organization. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_invitations",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/message": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Create message",
        "description": "Create message. Messages are attached to topics in order to coordinate memory of gen-AI chat sessions.Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "create_message",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Message"
        ],
        "summary": "Edit message",
        "description": "This will delete the specified message and replace it with a new message. All messages after the message being edited in the sort order will be deleted. The new message will be generated by the AI based on the new content provided in the request body. The response will include Chunks first on the stream if the topic is using RAG. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information. Auth'ed user or api key must have an admin or owner ro[...]",
        "operationId": "edit_message",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Message"
        ],
        "summary": "Regenerate message",
        "description": "Regenerate the assistant response to the last user message of a topic. This will delete the last message and replace it with a new message. The response will include Chunks first on the stream if the topic is using RAG. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "regenerate_message",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Message"
        ],
        "summary": "Regenerate message",
        "description": "Regenerate the assistant response to the last user message of a topic. This will delete the last message and replace it with a new message. The response will include Chunks first on the stream if the topic is using RAG. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "regenerate_message_patch",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message/edit_image": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Edit Image",
        "description": "Uses `gpt-image-1` to edit an images based on a given prompt. Note that the images must be\nbase64 encoded and all must have the same mime type.",
        "operationId": "edit_image",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message/generate_message_completions": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Generate Message Completions",
        "description": "Uses `openai` to generate a message completion for a given prompt.",
        "operationId": "generate_message_completions",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message/get_tool_function_params": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Get tool function parameters",
        "description": "This endpoint will generate the parameters for a tool function based on the user's message and image URL provided in the request body. The response will include the parameters for the tool function as a JSON object.",
        "operationId": "get_tool_function_params",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message/transcribe_audio": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Transcribe Audio",
        "description": "Uses `whisper-1` to transcribe an audio file passed in as a base64 encoded string.",
        "operationId": "transcribe_audio",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message/{message_id}": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Get a message by its ID",
        "description": "Quickly get the full object for a given message. From the message, you can get the topic and all messages which exist on that topic.",
        "operationId": "get_message_by_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/messages/{messages_topic_id}": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Get all messages for a given topic",
        "description": "If the topic is a RAG topic then the response will include Chunks first on each message. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information.",
        "operationId": "get_all_topic_messages",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/organization": {
      "post": {
        "tags": [
          "Organization"
        ],
        "summary": "Create Organization",
        "description": "Create a new organization. The auth'ed user who creates the organization will be the default owner of the organization.",
        "operationId": "create_organization",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Organization"
        ],
        "summary": "Update Organization",
        "description": "Update an organization. Only the owner of the organization can update it.",
        "operationId": "update_organization",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/organization/api_key": {
      "get": {
        "tags": [
          "Organization"
        ],
        "summary": "Get Organization Api Keys",
        "description": "Get the api keys which belong to the organization. The actual api key values are not returned, only the ids, names, and creation dates.",
        "operationId": "get_organization_api_keys",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Organization"
        ],
        "summary": "Create Organization Api Key",
        "description": "Create a new api key for the organization. Successful response will contain the newly created api key.",
        "operationId": "create_organization_api_key",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/organization/api_key/{api_key_id}": {
      "delete": {
        "tags": [
          "Organization"
        ],
        "summary": "Delete Organization Api Key",
        "description": "Delete an api key for the auth'ed organization.",
        "operationId": "delete_organization_api_key",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/organization/update_dataset_configs": {
      "post": {
        "tags": [
          "Organization"
        ],
        "summary": "Update All Dataset Configurations",
        "description": "Update the configurations for all datasets in an organization. Only the specified keys in the configuration object will be changed per dataset such that you can preserve dataset unique values. Auth'ed user or api key must have an owner role for the specified organization.",
        "operationId": "update_all_org_dataset_configs",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/organization/usage/{organization_id}": {
      "post": {
        "tags": [
          "Organization"
        ],
        "summary": "Get Organization Usage",
        "description": "Fetch the current usage specification of an organization by its id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_organization_usage",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/organization/users/{organization_id}": {
      "get": {
        "tags": [
          "Organization"
        ],
        "summary": "Get Organization Users",
        "description": "Fetch the users of an organization by its id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_organization_users",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/organization/{organization_id}": {
      "get": {
        "tags": [
          "Organization"
        ],
        "summary": "Get Organization",
        "description": "Fetch the details of an organization by its id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_organization",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Organization"
        ],
        "summary": "Delete Organization",
        "description": "Delete an organization by its id. The auth'ed user must be an owner of the organization to delete it.",
        "operationId": "delete_organization",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/public_page/{dataset_id}": {
      "get": {
        "tags": [
          "Public"
        ],
        "operationId": "public_page"
      }
    },
    "/api/shopify/plan_change": {
      "post": {
        "tags": [
          "Shopify"
        ],
        "operationId": "handle_shopify_plan_change"
      }
    },
    "/api/shopify/user_event": {
      "post": {
        "tags": [
          "Public"
        ],
        "summary": "Send a Shopify user event",
        "description": "This endpoint is used to send a Shopify user event to all users in the organization.",
        "operationId": "send_shopify_user_event"
      }
    },
    "/api/stripe/checkout/setup/{organization_id}": {
      "post": {
        "tags": [
          "Stripe"
        ],
        "summary": "Update Payment Method",
        "description": "Update a your payment method to a new one",
        "operationId": "update_payment_method",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/stripe/estimate_bill/{plan_id}": {
      "get": {
        "tags": [
          "Stripe"
        ],
        "summary": "Estimate Bill From Range",
        "description": "Return the amount you will be billed from a date range if you were on usage based pricing",
        "operationId": "estimate_bill_from_range",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/stripe/invoices/{organization_id}": {
      "get": {
        "tags": [
          "Stripe"
        ],
        "summary": "Get All Invoices",
        "description": "Get a list of all invoices",
        "operationId": "get_all_invoices",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/stripe/payment_link/{plan_id}/{organization_id}": {
      "get": {
        "tags": [
          "Stripe"
        ],
        "summary": "Checkout",
        "description": "Get a 303 SeeOther redirect link to the stripe checkout page for the plan and organization",
        "operationId": "direct_to_payment_link"
      }
    },
    "/api/stripe/plans": {
      "get": {
        "tags": [
          "Stripe"
        ],
        "summary": "Get All Plans",
        "description": "Get a list of all plans",
        "operationId": "get_all_plans"
      }
    },
    "/api/stripe/subscription/{subscription_id}": {
      "delete": {
        "tags": [
          "Stripe"
        ],
        "summary": "Cancel Subscription",
        "description": "Cancel a subscription by its id",
        "operationId": "cancel_subscription",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/stripe/subscription_plan/{subscription_id}/{plan_id}": {
      "patch": {
        "tags": [
          "Stripe"
        ],
        "summary": "Update Subscription Plan",
        "description": "Update a subscription to a new plan",
        "operationId": "update_subscription_plan",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/stripe/usage_plans": {
      "get": {
        "tags": [
          "Stripe"
        ],
        "summary": "Get All Usage Plans",
        "description": "Get a list of all usage_based plans",
        "operationId": "get_all_usage_plans"
      }
    },
    "/api/topic": {
      "post": {
        "tags": [
          "Topic"
        ],
        "summary": "Create Topic",
        "description": "Create a new chat topic. Topics are attached to a owner_id's and act as a coordinator for conversation message history of gen-AI chat sessions. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "create_topic",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Topic"
        ],
        "summary": "Update Topic",
        "description": "Update an existing chat topic. Currently, only the name of the topic can be updated. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "update_topic",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/topic/clone": {
      "post": {
        "tags": [
          "Topic"
        ],
        "summary": "Clone Topic",
        "description": "Create a new chat topic from a `topic_id`. The new topic will be attched to the owner_id and act as a coordinator for conversation message history of gen-AI chat sessions. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "clone_topic",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/topic/owner/{owner_id}": {
      "get": {
        "tags": [
          "Topic"
        ],
        "summary": "Get All Topics for Owner ID",
        "description": "Get all topics belonging to an arbitary owner_id. This is useful for managing message history and chat sessions. It is common to use a browser fingerprint or your user's id as the owner_id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "get_all_topics_for_owner_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/topic/{topic_id}": {
      "delete": {
        "tags": [
          "Topic"
        ],
        "summary": "Delete Topic",
        "description": "Delete an existing chat topic. When a topic is deleted, all associated chat messages are also deleted. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.",
        "operationId": "delete_topic",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/user": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update User Org Role",
        "description": "Update a user's information for the org specified via header. If the user_id is not provided, the auth'ed user will be updated. If the user_id is provided, the role of the auth'ed user or api key must be an admin (1) or owner (2) of the organization.",
        "operationId": "update_user",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/user/api_key": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User Api Keys",
        "description": "Get the api keys which belong to the auth'ed user. The actual api key values are not returned, only the ids, names, and creation dates.",
        "operationId": "get_user_api_keys",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/user/api_key/{api_key_id}": {
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete User Api Key",
        "description": "Delete an api key for the auth'ed user.",
        "operationId": "delete_user_api_key",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/metrics": {
      "post": {
        "tags": [
          "Metrics"
        ],
        "summary": "Get Prometheus Metrics",
        "description": "This route allows you to view the number of items in each queue in the Prometheus format.",
        "operationId": "get_metrics",
        "security": [
          {
            "X-API-KEY": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      },
      "X-API-KEY": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    }
  },
  "tags": [
    {
      "name": "Invitation",
      "description": "Invitation endpoint. Exists to invite users to an organization."
    },
    {
      "name": "Auth",
      "description": "Authentication endpoint. Serves to register and authenticate users."
    },
    {
      "name": "User",
      "description": "User endpoint. Enables you to modify user roles and information."
    },
    {
      "name": "Organization",
      "description": "Organization endpoint. Enables you to modify organization roles and information."
    },
    {
      "name": "Dataset",
      "description": "Dataset endpoint. Datasets belong to organizations and hold configuration information for both client and server. Datasets contain chunks and chunk groups."
    },
    {
      "name": "Chunk",
      "description": "Chunk endpoint. Think of chunks as individual searchable units of information. The majority of your integration will likely be with the Chunk endpoint."
    },
    {
      "name": "Chunk Group",
      "description": "Chunk groups endpoint. Think of a chunk_group as a bookmark folder within the dataset."
    },
    {
      "name": "Crawl",
      "description": "Crawl endpoint. Used to create and manage crawls for datasets."
    },
    {
      "name": "File",
      "description": "File endpoint. When files are uploaded, they are stored in S3 and broken up into chunks with text extraction from Apache Tika. You can upload files of pretty much any type up to 1GB in size. See chunking algorithm details at `docs.trieve.ai` for more information on how chunking works. Improved default chunking is on our roadmap."
    },
    {
      "name": "Events",
      "description": "Notifications endpoint. Files are uploaded asynchronously and events are sent to the user when the upload is complete."
    },
    {
      "name": "Topic",
      "description": "Topic chat endpoint. Think of topics as the storage system for gen-ai chat memory. Gen AI messages belong to topics."
    },
    {
      "name": "Message",
      "description": "Message chat endpoint. Messages are units belonging to a topic in the context of a chat with a LLM. There are system, user, and assistant messages."
    },
    {
      "name": "Stripe",
      "description": "Stripe endpoint. Used for the managed SaaS version of this app. Eventually this will become a micro-service. Reach out to the team using contact info found at `docs.trieve.ai` for more information."
    },
    {
      "name": "Health",
      "description": "Health check endpoint. Used to check if the server is up and running."
    },
    {
      "name": "Metrics",
      "description": "Metrics endpoint. Used to get information for monitoring"
    },
    {
      "name": "Analytics",
      "description": "Analytics endpoint. Used to get information for search and RAG analytics"
    },
    {
      "name": "Experiment",
      "description": "Experiment endpoint. Used to create and manage experiments"
    }
  ]
}
