-- Your SQL goes here
CREATE INDEX idx_file_upload_completed_notifications_user_uuid ON file_upload_completed_notifications (user_uuid);
CREATE INDEX idx_file_upload_completed_notifications_collection_uuid ON file_upload_completed_notifications (collection_uuid);
