# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.13.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ChunkReqPayloadFields(str, Enum):
    """
    The key in the ChunkReqPayload which you can map a column or field from the CSV or JSONL file to.
    """

    """
    allowed enum values
    """
    LINK = 'link'
    TAG_SET = 'tag_set'
    NUM_VALUE = 'num_value'
    TRACKING_ID = 'tracking_id'
    GROUP_TRACKING_IDS = 'group_tracking_ids'
    TIME_STAMP = 'time_stamp'
    LAT = 'lat'
    LON = 'lon'
    IMAGE_URLS = 'image_urls'
    WEIGHT = 'weight'
    BOOST_PHRASE = 'boost_phrase'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChunkReqPayloadFields from a JSON string"""
        return cls(json.loads(json_str))


