# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EventTypeRequest(str, Enum):
    """
    EventTypeRequest
    """

    """
    allowed enum values
    """
    FILE_UPLOADED = 'file_uploaded'
    FILE_UPLOAD_FAILED = 'file_upload_failed'
    CHUNKS_UPLOADED = 'chunks_uploaded'
    CHUNK_ACTION_FAILED = 'chunk_action_failed'
    CHUNK_UPDATED = 'chunk_updated'
    BULK_CHUNKS_DELETED = 'bulk_chunks_deleted'
    DATASET_DELETE_FAILED = 'dataset_delete_failed'
    QDRANT_UPLOAD_FAILED = 'qdrant_upload_failed'
    BULK_CHUNK_UPLOAD_FAILED = 'bulk_chunk_upload_failed'
    GROUP_CHUNKS_UPDATED = 'group_chunks_updated'
    GROUP_CHUNKS_ACTION_FAILED = 'group_chunks_action_failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventTypeRequest from a JSON string"""
        return cls(json.loads(json_str))


