# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.11.8
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RecommendType(str, Enum):
    """
    The type of recommendation to make. This lets you choose whether to recommend based off of `semantic` or `fulltext` similarity. The default is `semantic`.
    """

    """
    allowed enum values
    """
    SEMANTIC = 'semantic'
    FULLTEXT = 'fulltext'
    BM25 = 'bm25'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RecommendType from a JSON string"""
        return cls(json.loads(json_str))


