name: Create Shopify Server Images

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "clients/trieve-shopify-extension/**"

jobs:
  shopify-plugin:
    name: Push Shopify Plugin image
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            trieve/shopify-plugin
          tags: |
            type=raw,latest
            type=sha

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1.0.0-beta
        with:
          platforms: linux/amd64
          context: ./clients/trieve-shopify-extension/
          file: ./clients/trieve-shopify-extension/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
